Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2021-08, with the labels that each got.

#975 DX-1561: one-click fixes
  _includes/one-click-payments.md
  modules-sdks/index.md
Labels: documentation

#993 DX-1579: Removed Vipps Test Data
  payment-instruments/invoice/seamless-view.md
  resources/test-data.md
Labels: documentation

#1005 Searchyll release fixes (develop)
  .github/mergify.yml
  .github/release-drafter.yml
  .github/workflows/release-pr.yml
  _config.yml
Labels: config, fix

#1004 Searchyll release fixes (master)
  .github/mergify.yml
  .github/release-drafter.yml
  .github/workflows/release-pr.yml
  _config.yml
Labels: config, fix

#1011 Update Android documentation
  modules-sdks/mobile-sdk/android.md
  modules-sdks/mobile-sdk/plain-webview.md
Labels: documentation

#1122 DX-1584: Update dependencies
  Gemfile.lock
  package-lock.json
Labels: development

#1126 DX-1514: Disclaimer for instrument mode
  _includes/instrument-mode.md
Labels: documentation

#1125 DX-1585: Document that consumerProfileRef will expire after 24 hours.
  checkout/v2/checkin.md
Labels: documentation
