Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2021-02, with the labels that each got.

#830 Feature/dx-1488 moto hotfix
  _includes/moto.md
  _includes/payment-order-other-features.md
  payment-instruments/card/other-features.md
Labels: documentation

#833 dx-1492 remove moto from checkout
  _includes/payment-order-other-features.md
Labels: documentation

#834 DX-1492: Re-done with an if so payment menu still has it.
  _includes/payment-order-other-features.md
Labels: documentation

#835 Bump theme to version 1.9.10
  Gemfile
  Gemfile.lock
Labels: development, fix

#404 DX-112: Deploy to Azure
  .github/workflows/deploy_to_azure.yml
  .github/workflows/deploy_to_github_pages.yml
  checkout/features/core/index.md
  checkout/features/index.md
  checkout/features/optional/index.md
  checkout/features/technical-reference/index.md
  checkout/index.md
  gift-cards/index.md
  modules-sdks/index.md
  modules-sdks/mobile-sdk/index.md
  payment-instruments/card/features/core/index.md
  payment-instruments/card/features/index.md
  payment-instruments/card/features/optional/index.md
  payment-instruments/card/features/technical-reference/index.md
  payment-instruments/card/index.md
  payment-instruments/index.md
  payment-instruments/invoice/features/core/index.md
  payment-instruments/invoice/features/index.md
  payment-instruments/invoice/features/optional/index.md
  payment-instruments/invoice/features/technical-reference/index.md
  payment-instruments/invoice/index.md
  payment-instruments/mobile-pay/features/core/index.md
  payment-instruments/mobile-pay/features/index.md
  payment-instruments/mobile-pay/features/optional/index.md
  payment-instruments/mobile-pay/features/technical-reference/index.md
  payment-instruments/mobile-pay/index.md
  payment-instruments/swish/features/core/index.md
  payment-instruments/swish/features/index.md
  payment-instruments/swish/features/optional/index.md
  payment-instruments/swish/features/technical-reference/index.md
  payment-instruments/swish/index.md
  payment-instruments/trustly/features/core/index.md
  payment-instruments/trustly/features/index.md
  payment-instruments/trustly/features/optional/index.md
  payment-instruments/trustly/features/technical-reference/index.md
  payment-instruments/trustly/index.md
  payment-instruments/vipps/features/core/index.md
  payment-instruments/vipps/features/index.md
  payment-instruments/vipps/features/optional/index.md
  payment-instruments/vipps/features/technical-reference/index.md
  payment-instruments/vipps/index.md
  payment-menu/features/core/index.md
  payment-menu/features/index.md
  payment-menu/features/optional/index.md
  payment-menu/features/technical-reference/index.md
  payment-menu/index.md
  resources/development-guidelines/index.md
  resources/index.md
Labels: config, development, documentation

#839 Deploy to azure
  .github/workflows/deploy_to_azure.yml
Labels: config, fix

#840 DX-1500: Payment Menu in production (master)
  index.md
  payment-menu/after-payment.md
  payment-menu/capture.md
  payment-menu/index.md
  payment-menu/other-features.md
  payment-menu/payment-order.md
Labels: documentation, fix

#841 DX-1500: Payment Menu in production (develop)
  Gemfile
  Gemfile.lock
  _includes/cobadge-dankort.md
  _includes/moto.md
  _includes/payment-order-other-features.md
  index.md
  payment-menu/after-payment.md
  payment-menu/capture.md
  payment-menu/index.md
  payment-menu/payment-order.md
Labels: config, development, documentation

#842 DX-1501: Fix link verification
  .github/autolabeler.yml
  .github/scripts/commit-msg-test.sh
  .github/scripts/variables.sh
  .github/workflows/deploy_to_azure.yml
  .github/workflows/deploy_to_github_pages.yml
  .github/workflows/githooks.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/repository_metadata.sh
  .github/workflows/test.yml
  Gemfile
  Gemfile.lock
  _config.yml
  _layouts/redirect.html
  docker-compose.yml
Labels: config, development

#843 Feature/dx-1502 add tra section
  .github/scripts/variables.sh
  _includes/field-description-id.md
  _includes/tra.md
  checkout/features/index.md
  checkout/features/optional/index.md
  checkout/features/optional/tra.md
  checkout/features/optional/verify.md
Labels: config, development, documentation

#844 DX-1504: TRA fixes
  _includes/tra.md
  checkout/2.0/features/index.md
  checkout/2.0/features/optional/index.md
  checkout/2.0/features/optional/tra.md
Labels: documentation
