Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2021-04, with the labels that each got.

#897 DX-1531: Changed the if so only consumerprofileref is present in checkout
  _includes/payment-order-purchase.md
Labels: documentation

#896 DX-1530: Removed instrument from checkout and added disablePaymentMenu
  _includes/payment-order-purchase.md
  package-lock.json
  package.json
Labels: documentation

#899 DX-969: Add workflow for PR creation on release branch push
  .github/scripts/variables.sh
  .github/workflows/release-pr.yml
Labels: config, development

#898 ESY-2584 Add DK and FI for languages in paymentMenu
  _includes/field-description-language.md
  _includes/languages.md
Labels: documentation

#904 DX-1535: Fix response examples
  _includes/card-authorization-transaction.md
  _includes/instrument-mode.md
  _includes/metadata.md
  _includes/payment-order-purchase.md
  _includes/payments-operations.md
  checkout/v2/payment-menu.md
  payment-instruments/card/after-payment.md
  payment-instruments/invoice/direct.md
  payment-instruments/mobile-pay/seamless-view.md
  payment-instruments/swish/direct.md
  payment-instruments/swish/redirect.md
  payment-instruments/swish/seamless-view.md
  payment-instruments/trustly/redirect.md
  payment-instruments/trustly/seamless-view.md
  payment-instruments/vipps/after-payment.md
  payment-instruments/vipps/redirect.md
  payment-instruments/vipps/seamless-view.md
  payment-menu/payment-order.md
Labels: documentation

#912 Feature/dx 1538 remove non-card purchase sections
  _includes/create-payment.md
  checkout/v2/features/core/purchase.md
  checkout/v2/features/core/reversal.md
  checkout/v2/features/core/settlement-reconciliation.md
  payment-instruments/card/features/index.md
  payment-instruments/invoice/features/core/purchase.md
  payment-instruments/invoice/features/core/reversal.md
  payment-instruments/invoice/features/core/settlement-reconciliation.md
  payment-instruments/invoice/features/index.md
  payment-instruments/mobile-pay/features/core/purchase.md
  payment-instruments/mobile-pay/features/core/reversal.md
  payment-instruments/mobile-pay/features/core/settlement-reconciliation.md
  payment-instruments/mobile-pay/features/index.md
  payment-instruments/mobile-pay/seamless-view.md
  payment-instruments/swish/features/core/purchase.md
  payment-instruments/swish/features/core/reversal.md
  payment-instruments/swish/features/core/settlement-reconciliation.md
  payment-instruments/swish/features/index.md
  payment-instruments/swish/redirect.md
  payment-instruments/trustly/features/core/purchase.md
  payment-instruments/trustly/features/core/reversal.md
  payment-instruments/trustly/features/core/settlement-reconciliation.md
  payment-instruments/trustly/features/index.md
  payment-instruments/vipps/features/core/purchase.md
  payment-instruments/vipps/features/core/reversal.md
  payment-instruments/vipps/features/core/settlement-reconciliation.md
  payment-instruments/vipps/features/index.md
  payment-instruments/vipps/redirect.md
  payment-instruments/vipps/seamless-view.md
Labels: documentation

#913 feature/ESY-2591
  _includes/update-payment-order.md
Labels: documentation

#918 Release/2.2.0 (develop)
  .github/workflows/release-pr.yml
  package-lock.json
  rc.yaml
  resources/release-notes.md
Labels: config, development, documentation
