Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2021-06, with the labels that each got.

#952 Fix code example in tra.md
  _includes/tra.md
Labels: documentation

#953 DX-1570: Remove branch specifier for Searchyll
  Gemfile
Labels: development

#957 DX-1571: Configure Searchyll to index in stage environment
  _config.yml
  package-lock.json
Labels: config, development
