Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2021-11, with the labels that each got.

#1254 DX-1619: Hotfix Add tokens to paymentOrder GET response (master)
  _includes/payment-order-get.md
  modules-sdks/index.md
Labels: documentation, fix

#1255 Hotfix/dx 1619 add tokens to payment order get response (develop)
  _includes/payment-order-get.md
Labels: documentation, fix

#1257 DX-914: PlantUML theme
  Gemfile
  Gemfile.lock
  _config.yml
  checkout/v2/index.md
  docker-compose.yml
Labels: documentation, config, development

#1253 DX-1617: Checkout standard
  _includes/one-click-payments.md
  _includes/payment-order-capture.md
  _includes/payment-order-checkout-standard.md
  _includes/seamless-view-events.md
  checkout/v3/authenticated/features/optional/instrument-mode.md
  checkout/v3/authenticated/features/optional/moto.md
  checkout/v3/authenticated/features/optional/one-click-payments.md
  checkout/v3/authenticated/features/optional/recur.md
  checkout/v3/authenticated/features/optional/transaction-on-file.md
  checkout/v3/authenticated/features/optional/unscheduled.md
  checkout/v3/authenticated/features/optional/verify.md
  checkout/v3/authenticated/index.md
  checkout/v3/authenticated/seamless-view.md
  checkout/v3/get-started.md
  checkout/v3/index.md
  checkout/v3/mac/features/optional/instrument-mode.md
  checkout/v3/mac/features/optional/mac-payer-reference.md
  checkout/v3/mac/features/optional/moto.md
  checkout/v3/mac/features/optional/one-click-payments.md
  checkout/v3/mac/features/optional/recur.md
  checkout/v3/mac/features/optional/tra.md
  checkout/v3/mac/features/optional/unscheduled.md
  checkout/v3/mac/features/optional/verify.md
  checkout/v3/mac/index.md
  checkout/v3/sequence-diagrams.md
  checkout/v3/set-up.md
  checkout/v3/standard/features/optional/instrument-mode.md
  checkout/v3/standard/features/optional/moto.md
  checkout/v3/standard/features/optional/one-click-payments.md
  checkout/v3/standard/features/optional/recur.md
  checkout/v3/standard/features/optional/transaction-on-file.md
  checkout/v3/standard/features/optional/unscheduled.md
  checkout/v3/standard/features/optional/verify.md
  checkout/v3/standard/features/technical-reference/payment-menu-events.md
  checkout/v3/standard/index.md
  checkout/v3/standard/seamless-view.md
Labels: documentation

#1258 DX-1645: Fixed a rookie mistake with the link to Checkout v3 Standard
  checkout/v3/index.md
Labels: documentation
