Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2021-12, with the labels that each got.

#1260 DX-1637: Adding text for Set Up and Get Started
  checkout/v3/authenticated/index.md
  checkout/v3/authenticated/setup.md
  checkout/v3/get-started.md
  checkout/v3/index.md
  checkout/v3/mac/index.md
  checkout/v3/mac/setup.md
  checkout/v3/payments/index.md
  checkout/v3/payments/setup.md
  checkout/v3/standard/index.md
  checkout/v3/standard/setup.md
Labels: documentation

#1265 DX-1650: Fixed languages in Checkout v3
  _includes/languages.md
  checkout/v3/authenticated/index.md
  checkout/v3/mac/index.md
  checkout/v3/payments/index.md
  checkout/v3/standard/index.md
Labels: documentation

#1262 Feature/esy 3094 corporation limited menu
  _includes/corporate-limited-menu.md
  payment-menu/features/technical-reference/corporate-limited-menu.md
Labels: documentation

#1321 DX-1653 Switch to queue action
  .github/mergify.yml
Labels: config

#1325 DX-1660: Fix sidebar
  Gemfile
  Gemfile.lock
  _config.yml
  assets/puml-theme-swedbankpay.puml
Labels: documentation, config, development

#1326 Feature/dx 1632 new design for checkout v3
  Gemfile
  checkout/v3/authenticated/setup.md
  checkout/v3/index.md
  checkout/v3/mac/setup.md
  checkout/v3/payments/setup.md
  checkout/v3/set-up.md
  checkout/v3/standard/setup.md
  index.md
Labels: documentation, development

#1327 Feature/dx 1662 text fixes
  checkout/v3/index.md
  checkout/v3/standard/setup.md
  index.md
Labels: documentation
