Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2021-03, with the labels that each got.

#846 DX-1507: Bump theme from v1.9.10 to v1.9.13 to anonymize IP addresses in GA (master)
  Gemfile.lock
Labels: fix

#847 DX-1506: Removed estimated reading time
  checkout/3.0/index.md
  checkout/index.md
Labels: documentation

#848 DX-1507: Bump theme from v1.9.12 to v1.9.13 to anonymize IP addresses in GA (develop
  Gemfile.lock
Labels: fix

#849 DX-1035: Add search indexing with Searchyll
  .github/workflows/azure_production.yml
  .github/workflows/azure_stage.yml
  .github/workflows/github_pages_production.yml
  .github/workflows/github_pages_stage.yml
  .gitignore
  CODEOWNERS
  Gemfile
  Gemfile.lock
  _config.yml
Labels: config, development

#832 DX-1490 Fix externalNonPaymentToken
  _includes/card-authorization-transaction.md
  _includes/payments-operations.md
Labels: documentation

#852 DX-1503: Update SDKs & Modules
  _includes/alert-unsupported.md
  _includes/pluralize.md
  _includes/repository-table.md
  modules-sdks/index.md
Labels: documentation

#853 DX-1511: Moto changes again
  _includes/moto.md
Labels: documentation

#855 Hotfix/dx-1495 payment menu instrument to null and restrictToInstruments fixes (master)
  _includes/payment-order-purchase.md
Labels: config, development, documentation, fix

#856 Hotfix/dx-1495 payment menu instrument to null and RestrictToInstrument fixes (develop)
  _includes/payment-order-purchase.md
Labels: documentation

#859 DX-1495: Fixed the restrictedToInstruments table and a promt --> prompt typo (master)
  _includes/payment-order-purchase.md
  _includes/risk-indicator-table.md
Labels: documentation, fix

#863 DX-969: Add Release Drafter and Mergify
  .github/.mergify.yml
  .github/release-drafter.yml
  .github/workflows/auto-review-pull-requests.yml
  .github/workflows/azure-production.yml
  .github/workflows/azure-stage.yml
  .github/workflows/github-pages-production.yml
  .github/workflows/github-pages-stage.yml
  .github/workflows/release-drafter.yml
Labels: config

#864 DX-969: Adjust release drafter configuration
  .github/release-drafter.yml
Labels: config

#865 DX-969: Rename .mergify.yml to mergify.yml
  .github/mergify.yml
Labels: config

#866 DX-969: Change the order of categories
  .github/release-drafter.yml
Labels: config

#868 DX-1496: Changed CVC to Any on all the test cards
  resources/test-data.md
Labels: documentation

#869 DX-1499: Removed AutoCapture from intent in create purchase table for Vipps.
  payment-instruments/vipps/redirect.md
  payment-instruments/vipps/seamless-view.md
Labels: documentation

#870 DX-1519: Fixed approvedLegalAddress in the direct flow chart
  payment-instruments/invoice/direct.md
Labels: documentation

#871 DX-1520: Added an alert on the checkin site
  _includes/alert-checkin-agreement-required.md
  checkout/v2/checkin.md
Labels: documentation

#873 DX-1469: Changed a misleading gift card description
  _includes/gift-card-purchase.md
  gift-cards/operations.md
Labels: documentation

#874 Dx 1521 trying to downgrade theme
  Gemfile
  Gemfile.lock
  checkout/index.md
  checkout/v2/features/core/index.md
  checkout/v2/features/index.md
  checkout/v3/index.md
  modules-sdks/mobile-sdk/features/core/index.md
  modules-sdks/mobile-sdk/features/index.md
  modules-sdks/mobile-sdk/features/optional/index.md
  modules-sdks/mobile-sdk/features/technical-reference/index.md
  payment-instruments/invoice/features/index.md
  payment-menu/features/core/index.md
  payment-menu/features/index.md
Labels: development, documentation

#851 DX-1510: Updated IP address
  _includes/alert-ip-address.md
  _includes/callback.md
Labels: documentation

#875 Feature/dx 1495 payment menu instrument to null
  _includes/payer-aware-payment-menu.md
  _includes/transaction-on-file.md
  _includes/verify.md
  payment-menu/features/index.md
  payment-menu/features/optional/index.md
  payment-menu/features/optional/transaction-on-file.md
Labels: documentation

#881 DX-1526: Updated android sdk links
  _includes/alert-ip-address.md
  modules-sdks/mobile-sdk/android.md
Labels: documentation

#878 DX-1524: Changed Trustly from view-sales to view-sale
  _includes/payment-resource.md
  payment-instruments/trustly/seamless-view.md
Labels: documentation

#877 Feature/dx 1523 release round up task 1
  _includes/transaction-on-file.md
  checkout/v3/basic/features/core/payment-order-capture.md
  checkout/v3/dsca/features/core/payment-order-capture.md
  checkout/v3/standard/features/core/payment-order-capture.md
  checkout/v3/tailored/features/core/payment-order-capture.md
  payment-instruments/card/features/index.md
  payment-instruments/card/features/optional/index.md
  payment-instruments/card/features/optional/transaction-on-file.md
  payment-menu/features/optional/transaction-on-file.md
  resources/release-notes.md
Labels: documentation

#860 DX-1476: Fixed the restrictedToInstruments table and a promt --> prompt typo (develop)
  _includes/payment-order-purchase.md
  _includes/risk-indicator-table.md
Labels: documentation

#879 Hotfix/dx-1510 hotfixing the callback ip address (master)
  _includes/callback-reference.md
Labels: documentation, fix

#885 DX-1527: Fix risk indicator table
  _includes/purchase.md
  _includes/risk-indicator-table.md
Labels: documentation

#887 DX-1508: Downgrade theme to v1.9.13 again
  Gemfile
  Gemfile.lock
Labels: development

#886 DX-1525: termsOfServiceUrl
  _includes/field-description-termsofserviceurl.md
Labels: documentation

#888 Feature/dx-1468 card acceptance missing link
  _includes/card-general.md
Labels: documentation

#884 ESY-2578 Add basic explanation of unscheduled
  _includes/delete-payment-order-token.md
  _includes/payment-order-purchase.md
  _includes/payment-order-unscheduled.md
  _includes/purchase.md
  _includes/verify.md
  checkout/v2/features/optional/tra.md
  checkout/v2/features/optional/unscheduled.md
  checkout/v2/features/optional/verify.md
  checkout/v2/features/technical-reference/delete-token.md
  checkout/v3/basic/features/optional/unscheduled.md
  checkout/v3/basic/features/optional/verify.md
  checkout/v3/basic/features/technical-reference/delete-token.md
  checkout/v3/dsca/features/optional/unscheduled.md
  checkout/v3/dsca/features/optional/verify.md
  checkout/v3/dsca/features/technical-reference/delete-token.md
  checkout/v3/standard/features/optional/unscheduled.md
  checkout/v3/standard/features/optional/verify.md
  checkout/v3/standard/features/technical-reference/delete-token.md
  checkout/v3/tailored/features/optional/unscheduled.md
  checkout/v3/tailored/features/optional/verify.md
  checkout/v3/tailored/features/technical-reference/delete-token.md
  payment-menu/features/optional/transaction-on-file.md
  payment-menu/features/optional/unscheduled.md
  payment-menu/features/optional/verify.md
  payment-menu/features/technical-reference/delete-token.md
  resources/terminology.md
Labels: documentation

#894 DX-1529: Fixed checkout example after the "payment menu instrument to null" task
  _includes/payment-order-purchase.md
Labels: documentation

#895 ESY-2578 Add unscheduled token to po purchase, hide paymenttoken from co
  _includes/payment-order-purchase.md
  _includes/verify.md
Labels: documentation
