Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2022-11, with the labels that each got.

#1618 Feature/esy 3795 - Trustly SSN-Verification
  _includes/payment-order-ssn-restrictions.md
  checkout-v3/enterprise/features/optional/payer-restrictions.md
  checkout-v3/payments-only/features/optional/payer-restrictions.md
Labels: documentation

#1619 DX-1966: Reference Code cleanup
  _includes/cross-channel-payments.md
  checkout-v3/business/features/optional/cross-channel-payments.md
  checkout-v3/enterprise/features/optional/cross-channel-payments.md
  checkout-v3/payments-only/features/optional/cross-channel-payments.md
  checkout-v3/starter/features/optional/cross-channel-payments.md
Labels: documentation

#1613 DX-1952: required fields v3 icon removal
  _includes/autoclick.md
  _includes/checkoutv3-purchase.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-checkout-business.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-recur.md
  _includes/payment-order-unscheduled.md
  _includes/request-delivery-info.md
Labels: documentation

#1616 Feature/esy 4231
  _includes/payment-order-afd.md
  checkout-v3/payments-only/features/optional/afd.md
Labels: documentation

#1622 Feature/dx-1967 paid and cancelled cleanup
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
Labels: documentation

#1628 Feature/dx-1973 revert click to pay and screenshots
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
  _includes/instrument-mode.md
  _includes/request-delivery-info.md
  assets/img/checkout/checkin-enter-shipping-address.png
  assets/img/checkout/checkin-new-payer-ssn.png
  assets/img/checkout/checkin-new-payer.png
  assets/img/checkout/checkin-remember-me-digital.png
  assets/img/checkout/checkin-remember-me-mixed.png
  assets/img/checkout/checkin.png
  assets/img/checkout/checkout-v3-business-redirect.png
  assets/img/checkout/checkout-v3-business-seamless-menu.png
  assets/img/checkout/checkout-v3-redirect-menu.png
  assets/img/checkout/checkout-v3-seamless-menu.png
  checkout-v3/index.md
  checkout-v3/payments-only/seamless-view.md
  checkout-v3/starter/seamless-view.md
Labels: documentation

#1620 Feature/dx 1919 trustly verification
  _includes/payment-order-ssn-restrictions.md
  checkout-v3/enterprise/features/optional/payer-restrictions.md
  checkout-v3/payments-only/features/optional/payer-restrictions.md
Labels: documentation

#1623 DX-1953: Removed requireConsumerInfo from Starter
  _includes/payment-order-checkout-starter.md
  checkout-v3/starter/introduction.md
  checkout-v3/starter/seamless-view.md
Labels: documentation

#1626 Feature/dx 1947 problem section checkout
  _includes/problems/checkout.md
  _includes/problems/problems.md
  checkout-v2/features/technical-reference/problems.md
  checkout-v3/business/features/technical-reference/problems.md
  checkout-v3/enterprise/features/technical-reference/problems.md
  checkout-v3/payments-only/features/technical-reference/problems.md
  checkout-v3/starter/features/technical-reference/problems.md
  payment-menu/features/technical-reference/problems.md
Labels: documentation

#1634 DX-1978: Removed purchase from v3 tech ref
  checkout-v3/business/features/technical-reference/purchase.md
  checkout-v3/enterprise/features/technical-reference/purchase.md
  checkout-v3/payments-only/features/technical-reference/purchase.md
  checkout-v3/starter/features/technical-reference/purchase.md
Labels: documentation

#1638 DX-1977: Fix stage deploy
  .github/workflows/azure-stage.yml
Labels: config

#1624 DX-1956: Error in javascript example
  checkout-v3/business/seamless-view.md
  checkout-v3/enterprise/seamless-view.md
  checkout-v3/payments-only/seamless-view.md
  checkout-v3/starter/seamless-view.md
Labels: documentation

#1641 DX-1981: Added bullet point about org number in the v3 startup
  checkout-v3/business/index.md
  checkout-v3/enterprise/index.md
  checkout-v3/payments-only/index.md
  checkout-v3/starter/index.md
Labels: documentation

#1639 DX-1979: Removed payment state section from v3
  checkout-v3/business/features/technical-reference/payment-state.md
  checkout-v3/enterprise/features/technical-reference/payment-state.md
  checkout-v3/payments-only/features/technical-reference/payment-state.md
  checkout-v3/starter/features/technical-reference/payment-state.md
Labels: documentation

#1640 DX-1957: Removed transactions.md from v3 tech ref
  checkout-v3/business/features/technical-reference/transactions.md
  checkout-v3/enterprise/features/technical-reference/transactions.md
  checkout-v3/payments-only/features/technical-reference/transactions.md
  checkout-v3/starter/features/technical-reference/transactions.md
Labels: documentation

#1625 DX-1974: AFD cleanup
  .github/scripts/variables.sh
  .github/workflows/azure-production.yml
  .github/workflows/azure-stage.yml
  .github/workflows/github-pages-production.yml
  .github/workflows/github-pages-stage.yml
  .github/workflows/test.yml
  README.md
  _includes/payment-order-afd.md
  checkout-v3/business/features/optional/afd.md
  checkout-v3/enterprise/features/optional/afd.md
  checkout-v3/starter/features/optional/afd.md
  gift-cards/test-client.md
Labels: documentation, config, development

#1637 Feature/esy 3793_Swish_Age_Limit
  _includes/payment-order-age-restrictions.md
  checkout-v3/business/features/optional/age-restrictions.md
  checkout-v3/enterprise/features/optional/age-restrictions.md
  checkout-v3/payments-only/features/optional/age-restrictions.md
  checkout-v3/starter/features/optional/age-restrictions.md
Labels: documentation

#1644 DX-1984: Age Restriction Cosmetics
  _includes/payment-order-age-restrictions.md
  checkout-v3/business/features/optional/age-restrictions.md
  checkout-v3/enterprise/features/optional/age-restrictions.md
  checkout-v3/payments-only/features/optional/age-restrictions.md
  checkout-v3/starter/features/optional/age-restrictions.md
Labels: documentation

#1643 Feature/dx 1939 add payer model in resource model
  _includes/autoclick.md
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
  _includes/checkoutv3-purchase.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-abort.md
  _includes/payment-order-checkout-business.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-checkout-starter.md
  _includes/payment-order-get.md
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
  _includes/payment-order-unscheduled.md
  _includes/request-delivery-info.md
Labels: documentation

#1646 DX-1992: Fixed payer model table error
  _includes/checkout-v3-resource-models.md
Labels: documentation
