Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2022-07, with the labels that each got.

#1531 DX-1871: Fix payment url in unscheduled code example
  _includes/payment-order-unscheduled.md
Labels: documentation

#1535 Release 3.1.1 (master)
  Gemfile
  _includes/checkout-v3-resource-models.md
  _includes/complete-url.md
  _includes/enterprise.md
  _includes/mobile-sdk-papm.md
  _includes/mobile-sdk-tokens.md
  _includes/payment-order-unscheduled.md
  _includes/transaction-list-response.md
  _includes/transaction-response.md
  _includes/transaction.md
  _includes/transactions.md
  checkout-v3/business/features/technical-reference/transactions.md
  checkout-v3/business/features/technical-reference/urls.md
  checkout-v3/enterprise/features/optional/mac.md
  checkout-v3/enterprise/features/optional/recur.md
  checkout-v3/enterprise/features/optional/request-delivery-info.md
  checkout-v3/enterprise/features/optional/tra.md
  checkout-v3/enterprise/features/optional/unscheduled.md
  checkout-v3/enterprise/features/optional/verify.md
  checkout-v3/enterprise/features/technical-reference/transactions.md
  checkout-v3/enterprise/features/technical-reference/urls.md
  checkout-v3/starter/features/technical-reference/transactions.md
  checkout-v3/starter/features/technical-reference/urls.md
  modules-sdks/mobile-sdk/merchant-backend.md
  package-lock.json
  package.json
  resources/release-notes.md
Labels: documentation, development

#1536 Release 3.1.1 (develop)
  resources/release-notes.md
Labels: documentation

#1541 DX-1903: Change links to Mobile SDK from branch master to main
  .alexrc.yml
  _includes/autoclick.md
  _includes/checkoutv3-purchase.md
  _includes/corporate-limited-menu.md
  _includes/enterprise-payer-reference.md
  _includes/mobile-sdk-payment-order.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-checkout-business.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-checkout-starter.md
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
  _includes/payment-order-unscheduled.md
  _includes/purchase.md
  _includes/request-delivery-info.md
  _includes/tra.md
  _includes/unscheduled-purchase.md
  _includes/urls.md
  checkout-v2/checkin.md
  checkout-v2/index.md
  modules-sdks/mobile-sdk/merchant-backend-sample-code.md
  modules-sdks/mobile-sdk/merchant-backend-v2.md
  modules-sdks/mobile-sdk/merchant-backend.md
  payment-instruments/card/features/optional/moto.md
  payment-instruments/invoice/direct.md
  payment-instruments/invoice/redirect.md
  payment-instruments/invoice/seamless-view.md
  payment-instruments/mobile-pay/index.md
  payment-instruments/mobile-pay/redirect.md
  payment-instruments/swish/direct.md
  payment-instruments/swish/redirect.md
  payment-instruments/swish/seamless-view.md
  payment-instruments/trustly/redirect.md
  payment-instruments/trustly/seamless-view.md
  payment-instruments/vipps/redirect.md
  payment-instruments/vipps/seamless-view.md
  resources/development-guidelines/code-of-conduct.md
  resources/release-notes.md
Labels: documentation, config

#1542 DX-1904: Update license and badges
  LICENSE
  README.md
Labels: documentation, config, legal
