Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2022-01, with the labels that each got.

#1332 Hotfix DX-1669: Removed invoice specific parts of payment order capture section (master)
  .github/workflows/azure-production.yml
  .github/workflows/azure-stage.yml
  .github/workflows/test.yml
  _includes/payment-order-capture.md
Labels: documentation, config, fix

#1333 Hotfix DX-1669: Removed invoice specific parts of payment order capture section (develop)
  _includes/payment-order-capture.md
  modules-sdks/index.md
Labels: documentation, config, fix

#1336 DX-1672: Renamed `menuRestrictedToCorporateInstruments` to `corporateMode`
  _includes/corporate-limited-menu.md
Labels: documentation

#1339 Feature/dx 1665 remove cancel url from seamless view example
  _includes/purchase.md
  _includes/seamless-view-events.md
Labels: documentation

#1342 DX-1676 Bump Theme version to 1.15
  Gemfile
Labels: development

#1344 DX-1677 Make reviewdog ignore cancelled
  .github/workflows/test.yml
Labels: config

#1346 Hotfix/dx 1678 add missing slashes
  checkout-v3/index.md
  index.md
Labels: documentation, fix

#1349 DX-1680 Rearrange Checkout v3 in sidebar
  checkout-v3/authenticated/index.md
  checkout-v3/mac/index.md
  checkout-v3/payments/index.md
Labels: documentation

#1350 DX-1675: Added productName for recur, verify and unscheduled.
  _includes/payment-order-recur.md
  _includes/payment-order-unscheduled.md
  _includes/verify.md
Labels: documentation

#1351 DX-1682 Data Ownership
  checkout-v3/index.md
Labels: documentation, fix

#1356 DX-1691: Guest mode fixes
  _includes/payment-order-checkout-authenticate.md
  _includes/payment-order-checkout-mac.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-checkout-standard.md
  checkout-v3/authenticated/redirect.md
  checkout-v3/authenticated/seamless-view.md
  checkout-v3/mac/introduction.md
  checkout-v3/mac/redirect.md
  checkout-v3/mac/seamless-view.md
  checkout-v3/payments/introduction.md
  checkout-v3/payments/redirect.md
  checkout-v3/payments/seamless-view.md
  checkout-v3/standard/introduction.md
  checkout-v3/standard/seamless-view.md
Labels: documentation

#1359 DX-1689: Fixed the Checkout v3 operations.
  _includes/payment-order-operations.md
Labels: documentation

#1353 DX-1690: Removed transactions sections from checkout v3
  _includes/reversal.md
  _includes/seamless-view-events.md
  checkout-v3/authenticated/features/technical-reference/transactions.md
  checkout-v3/mac/features/technical-reference/transactions.md
  checkout-v3/standard/features/technical-reference/transactions.md
Labels: documentation

#1362 DX-1706: Integration and implementation field changes
  _includes/payment-order-checkout-authenticate.md
  _includes/payment-order-checkout-mac.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-checkout-standard.md
Labels: documentation

#1363 Feature/dx 1693 request model fixes
  _includes/checkoutv3-purchase.md
  _includes/field-description-orderitems.md
  _includes/payment-order-checkout-authenticate.md
  _includes/payment-order-checkout-mac.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-checkout-standard.md
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
  _includes/payment-order-unscheduled.md
  checkout-v3/authenticated/index.md
  checkout-v3/mac/index.md
  checkout-v3/payments-only/index.md
  checkout-v3/standard/index.md
  checkout-v3/standard/seamless-view.md
Labels: documentation

#1360 DX-1685: Updated the checkout v3 abort response
  _includes/payment-order-abort.md
  _includes/payment-order-expansions.md
  checkout-v3/authenticated/post-purchase.md
  checkout-v3/mac/post-purchase.md
  checkout-v3/payments-only/post-purchase.md
  checkout-v3/standard/post-purchase.md
Labels: documentation

#1358 DX-1688: Re-write status description
  _includes/payment-order-checkout-authenticate.md
  _includes/payment-order-checkout-mac.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-checkout-standard.md
Labels: documentation

#1369 DX-1717: Fixed wrong implementation in abort.
  _includes/payment-order-abort.md
Labels: documentation

#1374 DX-1614: Add Alex
  .github/workflows/alex.yml
  .github/workflows/misspell.yml
  .github/workflows/remark-lint.yml
  .github/workflows/test.yml
Labels: config

#1361 ESY-3224: Clarify usage of reccurenceToken and generateRecurrenceToken.
  _config.yml
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
Labels: documentation, config

#1365 DX-1704: Added a disclaimer regarding the onPaid event.
  checkout-v3/authenticated/seamless-view.md
  checkout-v3/mac/seamless-view.md
  checkout-v3/payments-only/seamless-view.md
  checkout-v3/standard/seamless-view.md
Labels: documentation

#1376 Feature/dx 1720 fix operation rels in cancel and reversal
  _includes/cancel.md
  _includes/checkoutv3-purchase.md
  _includes/mac-payer-reference.md
  _includes/payment-order-abort.md
  _includes/payment-order-checkout-authenticate.md
  _includes/payment-order-checkout-mac.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-checkout-standard.md
  _includes/payment-order-operations.md
  _includes/reversal.md
  checkout-v3/authenticated/seamless-view.md
  checkout-v3/standard/seamless-view.md
Labels: documentation

#1375 DX-1698: MAC sequence diagram updates
  checkout-v3/sequence-diagrams.md
Labels: documentation

#1371 DX-1714: Capture fixes
  _includes/api-resource.md
  _includes/payment-order-capture.md
Labels: documentation
