Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2022-09, with the labels that each got.

#1568 DX-1915 Add cache in GitHub Actions
  .github/workflows/test.yml
Labels: config

#1562 ESY-3870: Add siteId to payeeinfo-node for checkout3
  _includes/autoclick.md
  _includes/checkoutv3-purchase.md
  _includes/instrument-mode.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-checkout-business.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-checkout-starter.md
  _includes/payment-order-moto.md
  _includes/payment-order-recur.md
  _includes/payment-order-unscheduled.md
  _includes/request-delivery-info.md
  _includes/tra.md
  _includes/transaction-on-file.md
  _includes/verify.md
Labels: documentation

#1573 Release 3.1.2 (develop)
  resources/release-notes.md
Labels: documentation

#1574 ESY-4119: ESY-4118 MobilePay checkout
  _includes/request-delivery-info.md
Labels: documentation

#1575 DX-1920: Flesh out payeeReference info in table description
  _includes/autoclick.md
  _includes/cancel.md
  _includes/capture.md
  _includes/card-payments-capture.md
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
  _includes/checkoutv3-purchase.md
  _includes/corporate-limited-menu.md
  _includes/field-description-payee-reference.md
  _includes/invoice-capture.md
  _includes/mobilepay-payments-capture.md
  _includes/payee-info.md
  _includes/payee-reference.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-cancel.md
  _includes/payment-order-capture.md
  _includes/payment-order-checkout-business.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-checkout-starter.md
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
  _includes/payment-order-reversal.md
  _includes/payment-order-unscheduled.md
  _includes/purchase.md
  _includes/recurring-card-payments.md
  _includes/request-delivery-info.md
  _includes/reversal.md
  _includes/tra.md
  _includes/unscheduled-purchase.md
  _includes/vipps-payments-capture.md
  payment-instruments/card/after-payment.md
  payment-instruments/invoice/after-payment.md
  payment-instruments/invoice/direct.md
  payment-instruments/invoice/redirect.md
  payment-instruments/invoice/seamless-view.md
  payment-instruments/mobile-pay/after-payment.md
  payment-instruments/mobile-pay/redirect.md
  payment-instruments/mobile-pay/seamless-view.md
  payment-instruments/swish/after-payment.md
  payment-instruments/trustly/after-payment.md
  payment-instruments/vipps/after-payment.md
  payment-instruments/vipps/redirect.md
  payment-instruments/vipps/seamless-view.md
Labels: documentation

#1579 DX-1918: Instrument mode code example fixes
  _includes/instrument-mode.md
Labels: documentation

#1581 DX-1922: Balance Report Disclaimers
  _includes/alert-balance-report-samples.md
  _includes/alert-balance-report.md
  _includes/settlement-reconciliation.md
Labels: documentation

#1580 DX-1879: Adding returning purchases info in one click payments
  _includes/checkoutv3-purchase.md
  _includes/corporate-limited-menu.md
  _includes/custom-logo.md
  _includes/one-click-payments.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
  _includes/payment-order-unscheduled.md
  _includes/tra.md
Labels: documentation

#1578 DX-1895: Added paid nodes for other instruments.
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
Labels: documentation

#1566 DX-1911: Copied changes in feature includes 3-F
  _includes/3d-secure-2.md
  _includes/abort-reference.md
  _includes/authorizations.md
  _includes/callback.md
  _includes/cancel.md
  _includes/capture.md
  _includes/card-authorization-transaction.md
  _includes/checkout-v3-events.md
  _includes/cobadge-dankort.md
  _includes/description.md
  _includes/enterprise.md
  _includes/financing-consumer.md
Labels: documentation

#1571 DX-1914 Copied changes in feature includes R to V
  _includes/recurring-card-payments.md
  _includes/recurring-trustly-payments.md
  _includes/request-delivery-info.md
  _includes/reversal.md
  _includes/seamless-view-events.md
  _includes/settlement-reconciliation.md
  _includes/transaction-on-file.md
  _includes/transactions.md
  _includes/unscheduled-purchase-trustly.md
  _includes/unscheduled-purchase.md
  _includes/verify.md
Labels: documentation

#1582 DX-1913: Headers in feature sections starting with P
  _includes/payee-info.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-link.md
  _includes/payment-order-abort.md
  _includes/payment-order-after-payment.md
  _includes/payment-order-cancel.md
  _includes/payment-order-get.md
  _includes/payment-order-moto.md
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
  _includes/payment-order-unscheduled.md
  _includes/payment-resource.md
  _includes/payment-state.md
  _includes/payment-transaction-states.md
  _includes/payments-operations.md
  _includes/payout.md
  _includes/pba-tables.md
  _includes/prices.md
Labels: documentation

#1567 DX-1912: Copied changes in feature includes I - O
  _includes/invoice-authorization-transaction.md
  _includes/metadata.md
  _includes/moto.md
  _includes/one-click-payments.md
Labels: documentation, config

#1584 Release 3.1.3 (develop)
  resources/release-notes.md
Labels: documentation

#1589 DX-1791: Card MOTO Fixes
  _includes/moto.md
  payment-menu/features/optional/moto.md
Labels: documentation

#1588 DX-1923: Remove link to Direct section from Payment Instruments intro
  payment-instruments/index.md
Labels: documentation

#1592 Fixed typo in introduction.md
  introduction.md
Labels: documentation
