Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2022-12, with the labels that each got.

#1648 Release 3.1.5 (develop)
  _includes/autoclick.md
  _includes/checkout-v3-status-models.md
  _includes/checkoutv3-purchase.md
  _includes/fee-discount.md
  _includes/moto.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-recur.md
  _includes/payment-order-ssn-restrictions.md
  _includes/payment-order-unscheduled.md
  introduction.md
  payment-menu/features/optional/moto.md
  payment-menu/features/optional/verify.md
  resources/release-notes.md
Labels: documentation

#1655 DX-1994: Invoice fixes
  _includes/financing-consumer.md
  payment-instruments/invoice/redirect.md
Labels: documentation

#1653 ESY-4509 Add bin and msisdn to paid-model
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
Labels: documentation

#1656 DX-1959: Simon's misc docu errors
  _includes/payment-order-recur.md
  _includes/recurring-card-payments.md
  _includes/verify.md
Labels: documentation

#1650 ESY-4405 - Fixed documentation to fit with the reworked parameter
  _includes/payment-order-age-restrictions.md
Labels: documentation

#1657 DX-1958: Emphasized the need to reload payment menu.
  _includes/payment-url.md
Labels: documentation

#1660 DX-1995: V2 Events Cleanup
  _includes/seamless-view-events.md
Labels: documentation

#1661 DX-2003: Removed deprecated operations disclaimer and some lines from an example.
  _includes/payment-order-operations.md
  spec/support/verifier.rb
Labels: documentation, development

#1663 Release 3.1.6 (master)
  .github/workflows/rebase.yml
  Gemfile.lock
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
  _includes/financing-consumer.md
  _includes/payment-order-age-restrictions.md
  _includes/payment-order-operations.md
  _includes/payment-order-recur.md
  _includes/payment-url.md
  _includes/recurring-card-payments.md
  _includes/seamless-view-events.md
  _includes/verify.md
  package-lock.json
  package.json
  payment-instruments/invoice/redirect.md
  resources/release-notes.md
  spec/support/verifier.rb
Labels: documentation, config, development

#1664 Release 3.1.6 (develop)
  resources/release-notes.md
Labels: documentation
