Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2022-06, with the labels that each got.

#1501 DX-1849: Fixed example amount
  _includes/payment-order-purchase.md
Labels: documentation

#1499 DX-1840: Apple Pay cleanup
  _includes/autoclick.md
  checkout-v3/index.md
Labels: documentation

#1502 DX-1866: Add trace id in href
  _includes/autoclick.md
  _includes/checkout-v3-status-models.md
  _includes/checkoutv3-purchase.md
  _includes/instrument-mode.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-abort.md
  _includes/payment-order-checkout-business.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-checkout-starter.md
  _includes/payment-order-get.md
  _includes/payment-order-moto.md
  _includes/payment-order-operations.md
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
  _includes/payment-order-unscheduled.md
  _includes/request-delivery-info.md
  _includes/update-payment-order.md
  checkout-v2/payment-menu.md
  checkout-v3/business/redirect.md
  checkout-v3/business/seamless-view.md
  checkout-v3/enterprise/redirect.md
  checkout-v3/enterprise/seamless-view.md
  checkout-v3/payments-only/redirect.md
  checkout-v3/payments-only/seamless-view.md
  checkout-v3/starter/seamless-view.md
  modules-sdks/mobile-sdk/custom-backend.md
  modules-sdks/mobile-sdk/merchant-backend.md
  payment-menu/payment-order.md
Labels: documentation

#1506 DX-1867: Eligibility Check fix number ?
  _includes/instrument-mode.md
Labels: documentation

#1507 DX-1844: William's one-click issues, instruments edition
  _includes/one-click-payments.md
Labels: documentation

#1508 DX-1876: DevInfo payer node feedback
  _includes/request-delivery-info.md
  checkout-v3/business/features/optional/request-delivery-info.md
  checkout-v3/enterprise/features/optional/request-delivery-info.md
  checkout-v3/payments-only/features/optional/request-delivery-info.md
Labels: documentation

#1509 DX-1877: Autoclick icon
  checkout-v3/business/features/optional/autoclick.md
  checkout-v3/enterprise/features/optional/autoclick.md
  checkout-v3/payments-only/features/optional/autoclick.md
  checkout-v3/starter/features/optional/autoclick.md
Labels: documentation

#1510 DX-1873: Even more Eligibility Check
  _includes/instrument-mode.md
Labels: documentation

#1512 Feature/dx 1872 rewrite sdk intro
  _includes/mobile-sdk-observing-the-payment-process.md
  _includes/mobile-sdk-papm.md
  _includes/mobile-sdk-payment-order.md
  _includes/mobile-sdk-tokens.md
  _includes/mobile-sdk-verify.md
  checkout-v3/index.md
  modules-sdks/mobile-sdk/android.md
  modules-sdks/mobile-sdk/configuration.md
  modules-sdks/mobile-sdk/custom-backend.md
  modules-sdks/mobile-sdk/index.md
  modules-sdks/mobile-sdk/ios.md
  modules-sdks/mobile-sdk/merchant-backend-sample-code.md
  modules-sdks/mobile-sdk/merchant-backend-v2.md
  modules-sdks/mobile-sdk/merchant-backend.md
  modules-sdks/mobile-sdk/plain-webview.md
  modules-sdks/mobile-sdk/process-diagrams.md
Labels: documentation

#1514 DX-1882: Fixing request delivery info icon
  checkout-v3/business/features/optional/request-delivery-info.md
  checkout-v3/enterprise/features/optional/request-delivery-info.md
  checkout-v3/payments-only/features/optional/request-delivery-info.md
Labels: documentation

#1515 DX-1882: Fix request delivery info
  checkout-v3/business/features/optional/request-delivery-info.md
  checkout-v3/enterprise/features/optional/request-delivery-info.md
  checkout-v3/payments-only/features/optional/request-delivery-info.md
Labels: documentation

#1518 DX-1884: Added text center to starter screenshots
  checkout-v3/starter/seamless-view.md
Labels: documentation

#1519 DX-1885: Hide AutoClick from features
  checkout-v3/business/features/optional/autoclick.md
  checkout-v3/enterprise/features/optional/autoclick.md
  checkout-v3/payments-only/features/optional/autoclick.md
  checkout-v3/starter/features/optional/autoclick.md
Labels: documentation

#1525 Hotfix: Removed demoshop comment from Apple Pay release notes (master)
  resources/release-notes.md
Labels: documentation, fix

#1526 Hotfix: Removed demoshop comment from Apple Pay release notes (develop)
  resources/release-notes.md
Labels: documentation, fix

#1528 Removed consumers from V3
  _includes/mobile-sdk-papm.md
  _includes/mobile-sdk-tokens.md
  modules-sdks/mobile-sdk/merchant-backend.md
Labels: documentation

#1527 DX-1869: V2 TRA and MAC redirects wrong
  _includes/enterprise.md
  checkout-v3/enterprise/features/optional/mac.md
  checkout-v3/enterprise/features/optional/recur.md
  checkout-v3/enterprise/features/optional/request-delivery-info.md
  checkout-v3/enterprise/features/optional/tra.md
  checkout-v3/enterprise/features/optional/unscheduled.md
  checkout-v3/enterprise/features/optional/verify.md
Labels: documentation

#1534 DX-1890 Set theme version to 1.16
  Gemfile
Labels: development
