Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2023-02, with the labels that each got.

#1709 DX-2028: Downgrade theme from 2.0.0 to 1.16.2
  .github/mergify.yml
  Gemfile
  Gemfile.lock
Labels: config, development

#1672 DX-2004: Checkout v3 migration guide
  _includes/fields/aborted.md
  _includes/fields/cancelled.md
  _includes/fields/failed-attempts.md
  _includes/fields/failed.md
  _includes/fields/financial-transactions.md
  _includes/fields/history.md
  _includes/fields/paid.md
  _includes/fields/payer.md
  _includes/fields/status.md
  _includes/payment-order-abort.md
  _includes/status.md
  _includes/utils/documentation-section-url.md
  _plugins/clink_block.rb
  _plugins/flag_tag.rb
  checkout-v3/business/features/technical-reference/status.md
  checkout-v3/enterprise/features/technical-reference/status.md
  checkout-v3/migration-guide.md
  checkout-v3/payments-only/features/technical-reference/status.md
  checkout-v3/starter/features/technical-reference/status.md
Labels: documentation, development

#1717 Feature/dx 1942 add google pay
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
  _includes/instrument-mode.md
  _includes/request-delivery-info.md
  assets/img/googlepay-logo.svg
  checkout-v3/index.md
  checkout-v3/payment-presentations.md
  payment-instruments/index.md
Labels: documentation

#1720 DX-2046: Google Pay feedback round 2
  checkout-v3/payment-presentations.md
Labels: documentation

#1722 DX-2047: Google Pay feedback from Google
  checkout-v3/payment-presentations.md
Labels: documentation

#1724 DX-2053: Added trademark icon to all mentions of Google Pay
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
  _includes/instrument-mode.md
  _includes/request-delivery-info.md
  checkout-v3/payment-presentations.md
Labels: documentation

#1723 DX-2021: Added new screenshots for Enterprise and Payments Only
  assets/img/checkout/checkout-v3-redirect-menu.png
  assets/img/checkout/checkout-v3-seamless-menu.png
Labels: documentation

#1725 DX-2039: Test data OTP update
  assets/img/otp-challenge-form.png
  resources/test-data.md
Labels: documentation

#1721 TL-34: Adding documentation on how to use the Swedbank Pay Java SDK for integration between ECR and the terminal.
  modules-sdks/pax-terminal/index.md
  modules-sdks/pax-terminal/instore-solution/index.md
  modules-sdks/pax-terminal/instore-solution/java.md
Labels: documentation

#1729 DX-2057: Added transaction status description in top
  resources/test-data.md
Labels: documentation

#1695 DX-1845: One Click Payments issues in payments only
  _includes/one-click-payments.md
Labels: documentation

#1732 DX-2059 Update Theme version
  Gemfile
  Gemfile.lock
  _includes/autoclick.md
  _includes/capture.md
  _includes/card-authorization-transaction.md
  _includes/card-payments-capture.md
  _includes/checkout-v2-resource-models.md
  _includes/checkout-v2-status-models.md
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
  _includes/checkoutv3-purchase.md
  _includes/cross-channel-payments.md
  _includes/invoice-authorization-transaction.md
  _includes/payee-info.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-abort.md
  _includes/payment-order-after-payment.md
  _includes/payment-order-cancel.md
  _includes/payment-order-capture.md
  _includes/payment-order-checkout-business.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-checkout-starter.md
  _includes/payment-order-get.md
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
  _includes/payment-order-reversal.md
  _includes/payment-order-unscheduled.md
  _includes/payment-resource.md
  _includes/payments-operations.md
  _includes/prices.md
  _includes/problems/problems.md
  _includes/purchase.md
  _includes/request-delivery-info.md
  _includes/reversal.md
  _includes/transaction-list-response.md
  _includes/transaction-response.md
  _includes/unscheduled-purchase.md
  _includes/update-payment-order.md
  _includes/urls.md
  checkout-v2/checkin.md
  checkout-v2/payment-menu.md
  checkout-v3/migration-guide.md
  payment-instruments/card/after-payment.md
  payment-instruments/invoice/direct.md
  payment-instruments/mobile-pay/redirect.md
  payment-instruments/swish/direct.md
  payment-instruments/vipps/redirect.md
  payment-menu/payment-order.md
  spec/support/verifier.rb
Labels: documentation, development
