Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2023-11, with the labels that each got.

#2018 DX-2260: Added new events in history node
  _includes/checkout-v3-resource-models.md
Labels: documentation

#2019 DX-2258: Add one-click table
  _includes/checkout-v3-resource-models.md
  _includes/one-click-payments.md
  checkout-v3/payment-request-3-1.md
Labels: documentation

#2021 DX-2256: Changed a plethora of request and response headers
  _includes/autoclick.md
  _includes/checkoutv3-purchase.md
  _includes/delete-payment-order-token.md
  _includes/instrument-mode.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-abort.md
  _includes/payment-order-afd.md
  _includes/payment-order-after-payment.md
  _includes/payment-order-age-restrictions.md
  _includes/payment-order-cancel.md
  _includes/payment-order-capture.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-get.md
  _includes/payment-order-moto.md
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
  _includes/payment-order-reversal.md
  _includes/payment-order-ssn-restrictions.md
  _includes/payment-order-unscheduled.md
  _includes/payout.md
  _includes/request-delivery-info.md
  _includes/tra.md
  _includes/update-payment-order.md
  _includes/verify.md
  checkout-v3/payment-request-3-1.md
Labels: documentation

#2022 Added new function signatures of interface, and release notes
  pax-terminal/NET/Methods/abortasync.md
  pax-terminal/NET/Methods/closeasync.md
  pax-terminal/NET/Methods/continue.md
  pax-terminal/NET/Methods/create.md
  pax-terminal/NET/Methods/getlasttransactionresult.md
  pax-terminal/NET/Methods/getpaymentinstrumentasync.md
  pax-terminal/NET/Methods/openasync.md
  pax-terminal/NET/Methods/paymentasync.md
  pax-terminal/NET/Methods/refundasync.md
  pax-terminal/NET/Methods/requestcustomerconfirmation.md
  pax-terminal/NET/Methods/requestcustomerdigitstring.md
  pax-terminal/NET/Methods/requesttodisplayasync.md
  pax-terminal/NET/Methods/reverselastasync.md
  pax-terminal/NET/Methods/setpaymentinstrument.md
  pax-terminal/NET/Methods/start.md
  pax-terminal/NET/Methods/updateterminalasync.md
  pax-terminal/NET/index.md
  pax-terminal/NET/release-notes.md
  pax-terminal/NET/transactionsetup.md
  pax-terminal/release-notes.md
Labels: documentation

#2023 DX-2269: Fixed a lot of stuff after Kristiansen feedback
  _includes/autoclick.md
  _includes/callback.md
  _includes/checkoutv3-purchase.md
  _includes/instrument-mode.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-3-1.md
  _includes/payment-order-afd.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-moto.md
  _includes/payment-order-recur.md
  _includes/payment-order-unscheduled.md
  _includes/payout.md
  _includes/request-delivery-info.md
  _includes/tra.md
  _includes/verify.md
  checkout-v3/payment-presentations.md
  checkout-v3/payment-request-3-1.md
Labels: documentation

#2024 DX-2272: Added some trustly info
  _includes/payer-aware-payment-menu.md
Labels: documentation

#2025 DX-2271: Added a new failedattempts node for Vipps.
  _includes/checkout-v3-resource-models.md
Labels: documentation

#2026 DX-2270: Added info regarding the problem json in post purchase
  checkout-v3/post-purchase-3-1.md
  checkout-v3/post-purchase.md
Labels: documentation

#2027 DX-2270: Added number to callback and postpurchasefailedattempts
  _includes/callback.md
  _includes/checkout-v3-resource-models.md
  checkout-v3/post-purchase-3-1.md
  checkout-v3/post-purchase.md
Labels: documentation

#2028 DX-2274: Added capture tag
  _includes/callback.md
Labels: documentation

#2030 Release 4.6.0 (develop)
  checkout-v3/resources/release-notes.md
Labels: documentation

#2031 Develop-pos
  .github/workflows/azure-production-new.yml
  .github/workflows/azure-stage-new.yml
  .github/workflows/azure-stage-pos.yml
Labels: config

#2032 DX-2276: Added use case section
  _includes/use-case-subscriptions.md
  checkout-v3/features/index.md
  checkout-v3/index.md
  checkout-v3/migration-guide.md
  checkout-v3/modules-sdks/index.md
  checkout-v3/resources/index.md
  checkout-v3/setup.md
  checkout-v3/styling-info.md
  checkout-v3/use-cases/index.md
  checkout-v3/use-cases/subscriptions.md
Labels: documentation

#2033 DX-2279: Added / to url
  checkout-v3/index.md
Labels: documentation

#2038 DX-2281: Test data update (master)
  assets/img/new-otp-challenge-form.png
  checkout-v3/resources/test-data.md
Labels: documentation, fix

#2039 DX 2281: test data update (develop)
  .github/workflows/azure-production-new.yml
  .github/workflows/azure-stage-new.yml
  .github/workflows/azure-stage-pos.yml
  assets/img/new-otp-challenge-form.png
  checkout-v3/resources/test-data.md
Labels: documentation, config, fix

#2040 DX-2275: The progress so far. Checking in to do a hotfix.
  _includes/autoclick.md
  _includes/checkout-v3-resource-models.md
  _includes/checkoutv3-purchase.md
  _includes/corporate-limited-menu.md
  _includes/one-click-payments.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-3-1.md
  _includes/payment-order-abort.md
  _includes/payment-order-afd.md
  _includes/payment-order-cancel-3-1.md
  _includes/payment-order-capture-3-1.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-get.md
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
  _includes/payment-order-reversal-3-1.md
  _includes/payment-order-unscheduled.md
  _includes/payment-resource.md
  _includes/payout.md
  _includes/purchase.md
  _includes/recurring-card-payments.md
  _includes/request-delivery-info.md
  _includes/tra.md
  _includes/transaction-on-file.md
  _includes/transaction-response.md
  _includes/transaction.md
  _includes/transactions.md
  _includes/unscheduled-purchase.md
  _includes/update-payment-order.md
  _includes/urls.md
  _includes/use-case-subscriptions.md
  checkout-v3/index.md
  checkout-v3/resources/fundamental-principles.md
  old-implementations/payment-instruments-v1/invoice/direct.md
  old-implementations/payment-instruments-v1/mobile-pay/redirect.md
  old-implementations/payment-instruments-v1/swish/direct.md
  old-implementations/payment-instruments-v1/vipps/redirect.md
Labels: documentation
