Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2023-01, with the labels that each got.

#1669 DX-2012: Text changes from Gabriella
  checkout-v3/index.md
  index.md
Labels: documentation

#1674 DX-1996: HTTP QUERY support
  Gemfile
  Gemfile.lock
  index.md
Labels: documentation, development

#1677 DX-2009: Replace node with field
  _includes/autoclick.md
  _includes/checkout-v3-resource-models.md
  _includes/payment-order-recur.md
  _includes/payment-order-ssn-restrictions.md
  _includes/payment-order-unscheduled.md
  _includes/request-delivery-info.md
  _includes/unscheduled-purchase.md
  checkout-v3/enterprise/redirect.md
  checkout-v3/enterprise/seamless-view.md
  checkout-v3/payments-only/redirect.md
  checkout-v3/payments-only/seamless-view.md
  introduction.md
Labels: documentation

#1676 DX-2007: Added update payment order to v3 feature sections
  _includes/update-payment-order.md
  checkout-v3/business/features/optional/update.md
  checkout-v3/business/features/optional/verify.md
  checkout-v3/enterprise/features/optional/update.md
  checkout-v3/enterprise/features/optional/verify.md
  checkout-v3/payments-only/features/optional/update.md
  checkout-v3/payments-only/features/optional/verify.md
  checkout-v3/starter/features/optional/update.md
  checkout-v3/starter/features/optional/verify.md
Labels: documentation

#1673 DX-2014: Remove Card Direct Completely
  payment-instruments/card/capture.md
  payment-instruments/card/direct.md
  payment-instruments/card/mobile-card-payments.md
  payment-instruments/index.md
  resources/release-notes.md
Labels: documentation

#1679 ESY-4554 Add implementation to checkout3 requests
  _includes/autoclick.md
  _includes/checkoutv3-purchase.md
  _includes/instrument-mode.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-afd.md
  _includes/payment-order-checkout-business.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-checkout-starter.md
  _includes/payment-order-moto.md
  _includes/payment-order-recur.md
  _includes/payment-order-unscheduled.md
  _includes/request-delivery-info.md
  _includes/tra.md
  _includes/transaction-on-file.md
  _includes/verify.md
  checkout-v3/business/redirect.md
  checkout-v3/business/seamless-view.md
  checkout-v3/enterprise/redirect.md
  checkout-v3/enterprise/seamless-view.md
  checkout-v3/index.md
  checkout-v3/starter/seamless-view.md
Labels: documentation

#1681 Feature/esy 4554
  _includes/payment-order-recur.md
Labels: documentation

#1682 Feature/dx 2018 add nonpayment and externalnonpaymenttoken
  _includes/checkout-v2-resource-models.md
  _includes/checkout-v2-status-models.md
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
  checkout-v2/features/technical-reference/resource-sub-models.md
  checkout-v2/features/technical-reference/seamless-view-events.md
  checkout-v2/features/technical-reference/status-models.md
  checkout-v2/features/technical-reference/transactions.md
  checkout-v2/features/technical-reference/urls.md
  payment-menu/features/technical-reference/resource-sub-models.md
  payment-menu/features/technical-reference/seamless-view-events.md
  payment-menu/features/technical-reference/status-models.md
  payment-menu/features/technical-reference/transactions.md
Labels: documentation

#1675 Feature/dx 1909 new balance report in settlement and recon
  _includes/settlement-reconciliation.md
  assets/documents/R1234-0001-Redovisningsservice.pdf
  assets/documents/R1234-0001-Redovisningsservice.xlsx
  assets/documents/R1234-0001-Redovisningsservice.xml
  assets/documents/R1234-0002-Eget-konto.pdf
  assets/documents/R1234-0002-Eget-konto.xlsx
  assets/documents/R1234-0002-Eget-konto.xml
  assets/documents/testredovisning-payexcheckout.pdf
  checkout-v3/starter/index.md
  resources/development-guidelines/index.md
Labels: documentation

#1684 DX-2022: Cleanup before 3.1.7
  _includes/settlement-reconciliation.md
Labels: documentation

#1686 Release 3.1.7 (develop)
  resources/release-notes.md
Labels: documentation

#1701 DX-2028: Set RubyGems version to 3.3.22
  .github/workflows/test.yml
Labels: config

#1691 Feature/dx 1997 create matrix for checkout v3
  assets/img/applepay-logo.svg
  assets/img/clicktopay-logo.svg
  assets/img/swedbank-pay-vertical-black.svg
  checkout-v3/index.md
Labels: documentation

#1703 DX-2032: Replaced the bland card icon with Swedbank Pay logo
  checkout-v3/index.md
Labels: documentation

#1705 Feature/dx 2033 New global icon
  assets/img/globe-icon-old.png
  assets/img/globe-icon.png
  assets/img/new-card-icon.svg
  checkout-v3/index.md
Labels: documentation

#1704 Feature/dx 2029 Merchant Portal updates
  _includes/field-description-orderitems.md
  _includes/settlement-reconciliation.md
  assets/img/globe-icon-too-big.png
  checkout-v2/index.md
  checkout-v3/business/index.md
  checkout-v3/enterprise/index.md
  checkout-v3/payments-only/index.md
  checkout-v3/starter/index.md
  gift-cards/index.md
  introduction.md
  modules-sdks/mobile-sdk/index.md
  payment-instruments/index.md
  payment-instruments/swish/after-payment.md
  payment-menu/index.md
  resources/terminology.md
Labels: documentation

#1706 Release 3.1.8 (master)
  .github/dependabot.yml
  .github/workflows/release-pr.yml
  .github/workflows/test.yml
  Gemfile.lock
  _includes/field-description-orderitems.md
  _includes/settlement-reconciliation.md
  assets/img/applepay-logo.svg
  assets/img/clicktopay-logo.svg
  assets/img/globe-icon-old.png
  assets/img/globe-icon-too-big.png
  assets/img/globe-icon.png
  assets/img/new-card-icon.svg
  assets/img/swedbank-pay-vertical-black.svg
  checkout-v2/index.md
  checkout-v3/business/index.md
  checkout-v3/enterprise/index.md
  checkout-v3/index.md
  checkout-v3/payments-only/index.md
  checkout-v3/starter/index.md
  gift-cards/index.md
  introduction.md
  modules-sdks/mobile-sdk/index.md
  package-lock.json
  package.json
  payment-instruments/index.md
  payment-instruments/swish/after-payment.md
  payment-menu/index.md
  resources/release-notes.md
  resources/terminology.md
Labels: documentation, config, development

#1707 Release 3.1.8 (develop)
  Gemfile
  Gemfile.lock
  resources/release-notes.md
Labels: documentation, development
