Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2023-08, with the labels that each got.

#1912 DX-2086: ProductCategory string length
  _includes/autoclick.md
  _includes/checkoutv3-purchase.md
  _includes/payee-info.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
  _includes/payment-order-unscheduled.md
  _includes/purchase.md
  _includes/recurring-card-payments.md
  _includes/request-delivery-info.md
  _includes/tra.md
  _includes/unscheduled-purchase.md
  old-implementations/payment-instruments-v1/invoice/direct.md
  old-implementations/payment-instruments-v1/invoice/redirect.md
  old-implementations/payment-instruments-v1/invoice/seamless-view.md
  old-implementations/payment-instruments-v1/mobile-pay/redirect.md
  old-implementations/payment-instruments-v1/mobile-pay/seamless-view.md
  old-implementations/payment-instruments-v1/swish/direct.md
  old-implementations/payment-instruments-v1/swish/redirect.md
  old-implementations/payment-instruments-v1/swish/seamless-view.md
  old-implementations/payment-instruments-v1/trustly/redirect.md
  old-implementations/payment-instruments-v1/trustly/seamless-view.md
  old-implementations/payment-instruments-v1/vipps/after-payment.md
  old-implementations/payment-instruments-v1/vipps/redirect.md
  old-implementations/payment-instruments-v1/vipps/seamless-view.md
Labels: documentation

#1914 DX-2153: Added paymentAccountReference in cc paid model
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
Labels: documentation

#1917 DX-2152: Removed google analytics from config file
  _config.yml
Labels: config

#1920 DX-2164: Changed response urls in capture and cancel examples
  _includes/payment-order-cancel.md
  _includes/payment-order-capture.md
Labels: documentation

#1922 DX-2078: Callback improvements
  _includes/callback.md
Labels: documentation

#1924 Dx 2156 for net sdk update info about i swp trm callback interface. Also DX-2154 and DX-2155
  pax-terminal/NET/Events/index.md
  pax-terminal/NET/ISwpTrmCallbackInterface/index.md
  pax-terminal/NET/Methods/abortasync.md
  pax-terminal/NET/Methods/closeasync.md
  pax-terminal/NET/Methods/continue.md
  pax-terminal/NET/Methods/create.md
  pax-terminal/NET/Methods/getlasttransactionresult.md
  pax-terminal/NET/Methods/getpaymentinstrumentasync.md
  pax-terminal/NET/Methods/index.md
  pax-terminal/NET/Methods/openasync.md
  pax-terminal/NET/Methods/paymentasync.md
  pax-terminal/NET/Methods/refundasync.md
  pax-terminal/NET/Methods/requestcustomerconfirmation.md
  pax-terminal/NET/Methods/requestcustomerdigitstring.md
  pax-terminal/NET/Methods/requesttodisplayasync.md
  pax-terminal/NET/Methods/reverselastasync.md
  pax-terminal/NET/Methods/setpaymentinstrument.md
  pax-terminal/NET/Methods/start.md
  pax-terminal/NET/Methods/updateterminalasync.md
  pax-terminal/NET/index.md
  pax-terminal/index.md
Labels: documentation

#1925 Dx 2169 update payment request async and its result as of terminal version 1 2 17
  pax-terminal/NET/Methods/paymentasync.md
  pax-terminal/NET/Methods/start.md
Labels: documentation

#1927 DX-2160: Network Tokenization section
  _includes/network-tokenization.md
  checkout-v3/features/optional/network-tokenization.md
  checkout-v3/features/optional/one-click-payments.md
  checkout-v3/features/optional/order-items.md
  checkout-v3/features/optional/payer-aware-payment-menu.md
  checkout-v3/features/optional/payer-restrictions.md
  checkout-v3/features/optional/payout.md
  checkout-v3/features/optional/recur.md
  checkout-v3/features/optional/request-delivery-info.md
  checkout-v3/features/optional/split-settlement.md
  checkout-v3/features/optional/tos.md
  checkout-v3/features/optional/unscheduled.md
  checkout-v3/features/optional/verify.md
Labels: documentation

#1928 DX-2170: Added order items in basic payment order request
  _includes/order-items.md
  _includes/payment-order-checkout-payments-only.md
Labels: documentation

#1929 DX-2166: Fixed checkout-v3 error in url
  _includes/fee-discount.md
  _includes/verify.md
Labels: documentation

#1930 DX-2172: Network Tokenization feedback from Trond
  _includes/network-tokenization.md
Labels: documentation

#1931 DX-2065: Update Trustly Unscheduled Disclaimer and callback info
  _includes/unscheduled-purchase-trustly.md
Labels: documentation

#1932 DX-2174: Updates after Henrik's NWT feedback
  _includes/network-tokenization.md
Labels: documentation

#1918 Update-theme
  Gemfile
  Gemfile.lock
  _config.yml
Labels: config, development

#1935 DX-2178: Fix payeeReference description
  _includes/fields/payee-reference.md
Labels: documentation

#1936 DX-2173: Add delete payerownedtokens to delete tokens
  checkout-v3/features/optional/delete-token.md
  old-implementations/checkout-v2/features/optional/delete-token.md
  old-implementations/payment-menu-v2/features/optional/delete-token.md
Labels: documentation

#1938 DX-2185: Typos in NWT
  _includes/network-tokenization.md
Labels: documentation

#1939 DX-2184: Adding TokenType to payerownedTokens
  _includes/delete-payment-order-token.md
Labels: documentation

#1940 DX-2171: Section names instead of implementations in urls
  _includes/api-resource.md
  _includes/delete-payment-order-token.md
  _includes/description.md
Labels: documentation

#1941 DX-2186: Last cleanups
  _includes/frictionless-payments.md
  _includes/network-tokenization.md
  _includes/transaction-list-response.md
  checkout-v3/features/optional/delete-token.md
  old-implementations/checkout-v2/features/optional/delete-token.md
  old-implementations/payment-menu-v2/features/optional/delete-token.md
Labels: documentation

#1943 Release 4.4.0 (develop)
  checkout-v3/resources/release-notes.md
Labels: documentation
