Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2024-06, with the labels that each got.

#2288 DEVP-402: Moved all custom features to a new section
  _includes/expand-method.md
  checkout-v3/features/customize-ui/action-specific-text-on-payment-button.md
  checkout-v3/features/customize-ui/custom-logo.md
  checkout-v3/features/customize-ui/custom-styling.md
  checkout-v3/features/customize-ui/expand-method.md
  checkout-v3/features/customize-ui/index.md
  checkout-v3/features/customize-ui/instrument-mode.md
  checkout-v3/features/customize-ui/sort-order-payment-menu.md
  checkout-v3/features/customize-ui/tos.md
  checkout-v3/features/optional/index.md
  checkout-v3/release-notes.md
Labels: documentation

#2289 DEVP-405: Created settlement section
  checkout-v3/features/balancing-the-books/index.md
  checkout-v3/features/balancing-the-books/settlement-reconciliation.md
  checkout-v3/features/balancing-the-books/split-settlement.md
  checkout-v3/features/core/abort.md
  checkout-v3/features/core/callback.md
  checkout-v3/features/core/cancel.md
  checkout-v3/features/core/frictionless-payments.md
  checkout-v3/features/core/index.md
  checkout-v3/features/core/payment-order-capture.md
  checkout-v3/features/core/reversal.md
  checkout-v3/features/core/update.md
  checkout-v3/features/customize-ui/action-specific-text-on-payment-button.md
  checkout-v3/features/customize-ui/custom-logo.md
  checkout-v3/features/customize-ui/custom-styling.md
  checkout-v3/features/customize-ui/expand-method.md
  checkout-v3/features/customize-ui/index.md
  checkout-v3/features/customize-ui/instrument-mode.md
  checkout-v3/features/customize-ui/sort-order-payment-menu.md
  checkout-v3/features/optional/afd.md
  checkout-v3/features/optional/age-restrictions.md
  checkout-v3/features/optional/corporate-limited-menu.md
  checkout-v3/features/optional/delete-token.md
  checkout-v3/features/optional/fees-discounts.md
  checkout-v3/features/optional/index.md
  checkout-v3/features/optional/integrated-commerce.md
  checkout-v3/features/optional/moto.md
  checkout-v3/features/optional/network-tokenization.md
  checkout-v3/features/optional/one-click-payments.md
  checkout-v3/features/optional/order-items.md
  checkout-v3/features/optional/payer-aware-payment-menu.md
  checkout-v3/features/optional/payer-restrictions.md
  checkout-v3/features/optional/payment-link.md
  checkout-v3/features/optional/payout.md
  checkout-v3/features/optional/recur.md
  checkout-v3/features/optional/request-delivery-info.md
  checkout-v3/features/optional/unscheduled.md
  checkout-v3/features/optional/verify.md
  checkout-v3/features/technical-reference/index.md
  checkout-v3/get-started/index.md
Labels: documentation

#2291 add ecom and sdk workflows
  .github/workflows/azure-stage-ecom.yml
  .github/workflows/azure-stage-sdk.yml
Labels: config

#2292 DEVP-410: Added new error handling for invoice and credit account
  _includes/problems/checkout.md
  _includes/problems/credit-account.md
  _includes/problems/invoice.md
  _includes/problems/old-implementations/payment-instruments-v1/checkout.md
  _includes/problems/old-implementations/payment-instruments-v1/credit-account.md
  _includes/problems/old-implementations/payment-instruments-v1/invoice.md
Labels: documentation

#2293 DEVP-411: Invoice / CA feedback and restructure
  _includes/problems/checkout.md
  _includes/problems/credit-account.md
  _includes/problems/invoice.md
  _includes/problems/old-implementations/payment-instruments-v1/checkout.md
  _includes/problems/old-implementations/payment-instruments-v1/invoice.md
Labels: documentation

#2294 DEVP-406: Renamed from credit account to installment account
  _includes/problems/checkout.md
  _includes/problems/installment-account.md
  _includes/problems/old-implementations/payment-instruments-v1/checkout.md
  _includes/problems/old-implementations/payment-instruments-v1/installment-account.md
Labels: documentation

#2295 DEVP-412: Updated Benevity link
  checkout-v3/payment-presentations.md
Labels: documentation

#2296 DEVP-408: Lots of cleanup
  _includes/autoclick.md
  _includes/checkoutv3-purchase.md
  _includes/custom-logo.md
  _includes/fields/logo-url.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
  _includes/payment-order-unscheduled.md
  _includes/payout.md
  _includes/request-delivery-info.md
  _includes/tra.md
  checkout-v3/test-data.md
Labels: documentation

#2298 DEVP-415: Last minute language fixes
  _includes/autoclick.md
  _includes/checkout-v2-resource-models.md
  _includes/checkout-v2-status-models.md
  _includes/checkout-v3-events.md
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
  _includes/checkoutv3-purchase.md
  _includes/corporate-limited-menu.md
  _includes/expand-method.md
  _includes/fee-discount.md
  _includes/fields/amount.md
  _includes/instrument-mode.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-age-restrictions.md
  _includes/payment-order-cancel-3-1.md
  _includes/payment-order-cancel-combined.md
  _includes/payment-order-capture-3-1.md
  _includes/payment-order-capture-combined.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-recur.md
  _includes/payment-order-reversal-3-1.md
  _includes/payment-order-reversal-combined.md
  _includes/payment-order-ssn-restrictions.md
  _includes/payment-order-unscheduled.md
  _includes/payment-order-verify.md
  _includes/payout.md
  _includes/prices.md
  _includes/request-delivery-info.md
  _includes/seamless-view-events.md
  _includes/sort-order-payment-menu.md
  _includes/use-case-one-click.md
  _includes/use-case-recurring.md
  checkout-v3/features/customize-ui/expand-method.md
  checkout-v3/get-started/index.md
  checkout-v3/get-started/terminology.md
  checkout-v3/migration-guide.md
  checkout-v3/release-notes.md
  old-implementations/enterprise/features/optional/instrument-mode.md
  old-implementations/payment-instruments-v1/index.md
  old-implementations/payment-instruments-v1/mobile-pay/index.md
  old-implementations/payment-instruments-v1/swish/index.md
  old-implementations/payment-instruments-v1/trustly/index.md
  old-implementations/payment-instruments-v1/vipps/index.md
  old-implementations/payment-menu-v2/features/optional/instrument-mode.md
  old-implementations/payment-menu-v2/index.md
Labels: documentation

#2300 Release 5.3.0 (develop)
  checkout-v3/release-notes.md
Labels: documentation

#2302 DEVP-417: Added FailedAmount error code to installment account problems (master)
  _includes/problems/checkout.md
  _includes/problems/installment-account.md
  _includes/problems/old-implementations/payment-instruments-v1/checkout.md
  _includes/problems/old-implementations/payment-instruments-v1/installment-account.md
Labels: documentation, fix

#2303 DEVP-417: Added FailedAmount error code to installment account problems (develop)
  .github/workflows/azure-stage-ecom.yml
  .github/workflows/azure-stage-sdk.yml
  _includes/problems/checkout.md
  _includes/problems/installment-account.md
  _includes/problems/old-implementations/payment-instruments-v1/checkout.md
  _includes/problems/old-implementations/payment-instruments-v1/installment-account.md
Labels: documentation, config, fix

#2305 Hotfix: DEVP-420 Fix GET Tokens request (master)
  _includes/payer-aware-payment-menu.md
Labels: documentation, fix

#2307 DEVP-422: Hotfix of hotfix (master)
  _includes/one-click-payments.md
  _includes/payer-aware-payment-menu.md
  _includes/problems/checkout.md
  _includes/problems/old-implementations/payment-instruments-v1/checkout.md
Labels: documentation, fix

#2308 Hotfix devp 422 hotfix the hotfix (develop)
  _includes/one-click-payments.md
  _includes/payer-aware-payment-menu.md
  _includes/problems/checkout.md
  _includes/problems/old-implementations/payment-instruments-v1/checkout.md
Labels: documentation, fix

#2309 DEVP-422: Moved Corp Menu to Customize UI
  checkout-v3/features/customize-ui/corporate-limited-menu.md
  checkout-v3/features/customize-ui/custom-logo.md
  checkout-v3/features/customize-ui/custom-styling.md
  checkout-v3/features/customize-ui/expand-method.md
  checkout-v3/features/customize-ui/instrument-mode.md
  checkout-v3/features/customize-ui/sort-order-payment-menu.md
  checkout-v3/features/customize-ui/tos.md
Labels: documentation

#2311 DEVP-424: Rename Core to Payment Operations
  _includes/fields/callback-url.md
  _includes/fields/intent.md
  _includes/payment-link.md
  _includes/use-case-recurring.md
  checkout-v3/features/core/index.md
  checkout-v3/features/customize-payments/index.md
  checkout-v3/features/customize-ui/index.md
  checkout-v3/features/optional/index.md
  checkout-v3/features/payment-operations/abort.md
  checkout-v3/features/payment-operations/callback.md
  checkout-v3/features/payment-operations/cancel.md
  checkout-v3/features/payment-operations/index.md
  checkout-v3/features/payment-operations/payment-order-capture.md
  checkout-v3/features/payment-operations/reversal.md
  checkout-v3/features/payment-operations/update.md
  checkout-v3/features/technical-reference/index.md
  checkout-v3/get-started/display-payment-ui/redirect.md
  checkout-v3/get-started/display-payment-ui/seamless-view.md
  checkout-v3/get-started/payment-request-3-1.md
  checkout-v3/get-started/payment-request.md
  checkout-v3/get-started/terminology.md
  checkout-v3/migration-guide.md
  checkout-v3/release-notes.md
Labels: documentation
