Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2024-02, with the labels that each got.

#2098 DX-2314: Removed Unscheduled Token from response
  _includes/payment-order-unscheduled.md
Labels: documentation

#2102 nexo Retailer explained configurtation message
  pax-terminal/NET/SwpTrmLib/Methods/handy/requesttoprint.md
  pax-terminal/NET/tutorial/fuel-card-transaction.md
  pax-terminal/Nexo-Retailer/auto-configure-ecr-2-terminal.md
Labels: documentation

#2101 dx-2311 migration guide continued
  checkout-v3/migration-guide.md
Labels: documentation

#2104 explained TerminalAddressObtainedEventCallback
  pax-terminal/NET/release-notes.md
  pax-terminal/NET/tutorial/autoconfigurepos.md
  pax-terminal/Nexo-Retailer/auto-configure-ecr-2-terminal.md
  pax-terminal/release-notes.md
Labels: documentation

#2103 DX-2346: Removed episerver link, unsupported disclaimer and magento from text
  checkout-v3/modules-sdks/index.md
Labels: documentation

#2106 DX-2345: Removed sections no longer present from the resource intro
  checkout-v3/resources/index.md
Labels: documentation

#2109 DX-2332: Test commit to see if things work
  _includes/network-tokenization.md
  _includes/payment-order-3-1.md
  _includes/payment-order-checkout-payments-only.md
  checkout-v3/migration-guide.md
  checkout-v3/modules-sdks/index.md
  checkout-v3/modules-sdks/mobile-sdk/android.md
  checkout-v3/modules-sdks/mobile-sdk/configuration.md
  checkout-v3/modules-sdks/mobile-sdk/custom-backend.md
  checkout-v3/modules-sdks/mobile-sdk/ios.md
  checkout-v3/modules-sdks/mobile-sdk/merchant-backend-sample-code.md
  checkout-v3/modules-sdks/mobile-sdk/merchant-backend-v2.md
  checkout-v3/modules-sdks/mobile-sdk/merchant-backend.md
  checkout-v3/modules-sdks/mobile-sdk/plain-webview.md
  checkout-v3/modules-sdks/mobile-sdk/process-diagrams.md
  checkout-v3/payment-request-3-1.md
  checkout-v3/release-notes.md
  checkout-v3/test-data.md
  index.md
  old-implementations/checkout-v2/after-payment.md
  old-implementations/checkout-v2/capture.md
  old-implementations/checkout-v2/checkin.md
  old-implementations/checkout-v2/index.md
  old-implementations/checkout-v2/payment-menu.md
  old-implementations/enterprise/features/core/abort.md
  old-implementations/enterprise/features/core/callback.md
  old-implementations/enterprise/features/core/cancel.md
  old-implementations/enterprise/features/core/frictionless-payments.md
  old-implementations/enterprise/features/core/payment-order-capture.md
  old-implementations/enterprise/features/core/reversal.md
  old-implementations/enterprise/features/core/settlement-reconciliation.md
  old-implementations/enterprise/features/core/update.md
  old-implementations/enterprise/index.md
  old-implementations/enterprise/introduction.md
  old-implementations/enterprise/post-purchase.md
  old-implementations/enterprise/redirect.md
  old-implementations/enterprise/seamless-view.md
  old-implementations/payment-instruments-v1/card/after-payment.md
  old-implementations/payment-instruments-v1/card/capture.md
  old-implementations/payment-instruments-v1/card/index.md
  old-implementations/payment-instruments-v1/card/redirect.md
  old-implementations/payment-instruments-v1/card/seamless-view.md
  old-implementations/payment-instruments-v1/index.md
  old-implementations/payment-instruments-v1/invoice/after-payment.md
  old-implementations/payment-instruments-v1/invoice/capture.md
  old-implementations/payment-instruments-v1/invoice/direct.md
  old-implementations/payment-instruments-v1/invoice/index.md
  old-implementations/payment-instruments-v1/invoice/redirect.md
  old-implementations/payment-instruments-v1/invoice/seamless-view.md
  old-implementations/payment-menu-v2/after-payment.md
  old-implementations/payment-menu-v2/capture.md
  old-implementations/payment-menu-v2/index.md
  old-implementations/payment-menu-v2/payment-order.md
Labels: documentation

#2112 DX-2351: More failing links
  _includes/fields/description.md
  _includes/payment-order-3-1.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-reversal-3-1.md
  _includes/verify.md
  checkout-v3/features/technical-reference/payment-url.md
  old-implementations/checkout-v2/payment-menu.md
Labels: documentation

#2114 Release 4.7.0 (develop)
  checkout-v3/release-notes.md
Labels: documentation

#2117 Hotfix: DX-2358 Test Data Redirect link (Master)
  checkout-v3/test-data.md
Labels: documentation, fix

#2119 Hotfix: DX-2359 Token Inactive Url (Master)
  _includes/problems/checkout.md
Labels: documentation, fix

#2120 Hotfix: DX-2359 Token Inactive Url (Develop)
  _includes/problems/checkout.md
Labels: documentation, fix

#2122 DX-2240: Added new reattempts problems sections and new magic amounts
  _includes/payer-aware-payment-menu.md
  _includes/problems/checkout.md
  checkout-v3/test-data.md
Labels: documentation

#2123 DX-2363: Old implementations to bottom of menu order
  old-implementations/index.md
  pax-terminal/index.md
Labels: documentation

#2125 DX-2365: Renamed Digital Payments Release Notes
  checkout-v3/release-notes.md
Labels: documentation

#2126 DX-2364: Added "enablePaymentDetailsConsentCheckbox" to payment order and "paymentTokenGenerated" to paid.
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
  _includes/payment-order-3-1.md
  _includes/payment-order-checkout-payments-only.md
Labels: documentation

#2127 DX-2369: Added DisableStorePaymentDetails error message to Problems section
  _includes/problems/checkout.md
Labels: documentation

#2128 DX-2360: Switched to correct reversal include in checkout v3 core features
  checkout-v3/features/core/reversal.md
Labels: documentation

#2129 DX-2370: Removed consent checkbox from basic requests and added to one click
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
  _includes/one-click-payments.md
  _includes/payment-order-3-1.md
  _includes/payment-order-checkout-payments-only.md
Labels: documentation

#2130 DX-2371: Fixed consent checkbox header
  _includes/one-click-payments.md
Labels: documentation

#2131 DX-2338: Added first and last name to frictionless payments section
  _includes/frictionless-payments.md
Labels: documentation

#2132 Dx 2368 add info from pax 2562
  _includes/pax-saleitem.md
  pax-terminal/NET/SwpTrmLib/Methods/essential/openasync.md
  pax-terminal/NET/includes/transactionsetup.md
  pax-terminal/NET/release-notes.md
  pax-terminal/NET/tutorial/fuel-card-transaction.md
  pax-terminal/NET/tutorial/payment-with-orderid.md
  pax-terminal/Nexo-Retailer/Quick-guide/first-message.md
  pax-terminal/Nexo-Retailer/submit-purchse-order-number.md
  pax-terminal/release-notes.md
Labels: documentation

#2133 DX-2355: Added one-click use case
  _includes/use-case-one-click.md
  checkout-v3/use-cases/one-click.md
Labels: documentation

#2134 DX-2377: Added condition regarding Trustly
  _includes/fields/payment-url-paymentorder.md
  _includes/payment-order-3-1.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-purchase.md
  checkout-v3/use-cases/one-click.md
Labels: documentation

#2135 DX-2380: Added consent box in papm
  _includes/payer-aware-payment-menu.md
Labels: documentation

#2137 DX-2381: Cleaned up user case and fixed cards/link
  _includes/use-case-one-click.md
  checkout-v3/index.md
Labels: documentation

#2138 DX-2384: Changed a GET response as requested by Sigrid
  _includes/network-tokenization.md
Labels: documentation

#2139 DX-2385: Removed some tokens and added some fields
  _includes/network-tokenization.md
Labels: documentation

#2140 Release 4.8.0 (master)
  .github/workflows/pr-labeler.yml
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
  _includes/fields/payment-url-paymentorder.md
  _includes/frictionless-payments.md
  _includes/network-tokenization.md
  _includes/one-click-payments.md
  _includes/pax-saleitem.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-3-1.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-checkout-payments-only.md
  _includes/payment-order-purchase.md
  _includes/problems/checkout.md
  _includes/use-case-one-click.md
  checkout-v3/features/core/reversal.md
  checkout-v3/index.md
  checkout-v3/release-notes.md
  checkout-v3/test-data.md
  checkout-v3/use-cases/one-click.md
  old-implementations/index.md
  pax-terminal/NET/SwpTrmLib/Methods/essential/openasync.md
  pax-terminal/NET/includes/transactionsetup.md
  pax-terminal/NET/release-notes.md
  pax-terminal/NET/tutorial/fuel-card-transaction.md
  pax-terminal/NET/tutorial/payment-with-orderid.md
  pax-terminal/Nexo-Retailer/Quick-guide/first-message.md
  pax-terminal/Nexo-Retailer/submit-purchse-order-number.md
  pax-terminal/index.md
  pax-terminal/release-notes.md
Labels: documentation, config

#2141 Release 4.8.0 (develop)
  checkout-v3/release-notes.md
Labels: documentation

#2144 DX-2387: Added Public Migration Key to Resources again
  checkout-v3/resources/public-migration-key.md
Labels: documentation

#2145 Release 4.8.1 (master)
  Gemfile
  Gemfile.lock
  checkout-v3/resources/public-migration-key.md
  package-lock.json
  package.json
Labels: documentation, development
