Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2024-01, with the labels that each got.

#2062 DX-2304: Removing duplicate reversal info and added a sequence diagram
  _includes/payment-order-reversal-combined.md
Labels: documentation

#2063 DX-2303: Remove duplicate capture info
  _includes/payment-order-capture-combined.md
  checkout-v3/features/core/payment-order-capture.md
Labels: documentation

#2064 DX-2301: Updated the callback header
  _includes/callback.md
Labels: documentation

#2065 DX-2302: Removed duplicate cancel information and switched include
  _includes/payment-order-cancel-combined.md
  checkout-v3/features/core/cancel.md
Labels: documentation

#2069 DX-2298: Trying Årsets stage deploy fix.
  .github/workflows/azure-stage.yml
  checkout-v3/index.md
  checkout-v3/migration-guide.md
  checkout-v3/use-cases/index.md
Labels: documentation, config

#2066 DX-2296: Tried to add a new release notes section. Needs html work in theme repo.
  checkout-v3/resources/release-notes.md
  pax-terminal/index.md
Labels: documentation

#2070 DX-2142: Re-structured some information
  checkout-v3/display-payment-ui/index.md
  checkout-v3/display-payment-ui/redirect.md
  checkout-v3/payment-request-3-1.md
  checkout-v3/payment-request.md
Labels: documentation

#2075 DX-2322: Updated to theme 2.1.12.pre.beta.2
  Gemfile
  Gemfile.lock
Labels: development

#2078 DX-2308: Removed duplicate release notes from intro pages
  checkout-v3/index.md
  pax-terminal/index.md
Labels: documentation

#2079 DX-2334: Updated Apple Pay domain verification text
  checkout-v3/payment-presentations.md
Labels: documentation

#2080 DX-2324: Moved the partner cards to our front page and removed the partner page
  checkout-v3/resources/partners.md
  index.md
Labels: documentation

#2081 DX-2315: Removed the main menu styling page
  checkout-v3/styling-info.md
Labels: documentation

#2082 DX-2318: Moved Open Source Development Guidelines and updated links
  checkout-v3/index.md
  checkout-v3/modules-sdks/development-guidelines/code-of-conduct.md
  checkout-v3/modules-sdks/development-guidelines/contributing.md
  checkout-v3/modules-sdks/development-guidelines/good-commit-practice.md
  checkout-v3/modules-sdks/development-guidelines/index.md
  checkout-v3/modules-sdks/development-guidelines/license.md
Labels: documentation, legal

#2083 DX-2316: Moved data protection to old implementations checkout v2
  checkout-v3/resources/release-notes.md
  old-implementations/checkout-v2/checkin.md
  old-implementations/checkout-v2/data-protection.md
Labels: documentation

#2086 DX-2317: Moved release notes to sec nav
  checkout-v3/release-notes.md
Labels: documentation

#2088 DX-2335: SDK link removals
  _includes/use-case-recurring.md
  checkout-v3/modules-sdks/index.md
  checkout-v3/resources/public-migration-key.md
Labels: documentation

#2091 correceted example fuel payment response
  pax-terminal/Nexo-Retailer/fuelfunctionality.md
Labels: documentation

#2092 described manually entered payment instrument. Also corrected permalinks under NET
  pax-terminal/NET/SwpTrmLib/Methods/essential/abortasync.md
  pax-terminal/NET/SwpTrmLib/Methods/essential/closeasync.md
  pax-terminal/NET/SwpTrmLib/Methods/essential/create.md
  pax-terminal/NET/SwpTrmLib/Methods/essential/getlasttransactionresult.md
  pax-terminal/NET/SwpTrmLib/Methods/essential/openasync.md
  pax-terminal/NET/SwpTrmLib/Methods/essential/paymentasync.md
  pax-terminal/NET/SwpTrmLib/Methods/essential/refundasync.md
  pax-terminal/NET/SwpTrmLib/Methods/essential/start.md
  pax-terminal/NET/SwpTrmLib/Methods/handy/getpaymentinstrumentasync.md
  pax-terminal/NET/SwpTrmLib/Methods/handy/requestcustomerconfirmation.md
  pax-terminal/NET/SwpTrmLib/Methods/handy/requestcustomerdigitstring.md
  pax-terminal/NET/SwpTrmLib/Methods/handy/requesttodisplayasync.md
  pax-terminal/NET/SwpTrmLib/Methods/handy/requesttoprint.md
  pax-terminal/NET/SwpTrmLib/Methods/handy/setpaymentinstrument.md
  pax-terminal/NET/SwpTrmLib/Methods/otheravailable/continue.md
  pax-terminal/NET/SwpTrmLib/Methods/otheravailable/reverselastasync.md
  pax-terminal/NET/SwpTrmLib/Methods/otheravailable/updateterminalasync.md
  pax-terminal/NET/includes/transactionsetup.md
  pax-terminal/Nexo-Retailer/dialog-in-terminal.md
  pax-terminal/Nexo-Retailer/keyin-paymentinstrument.md
Labels: documentation

#2093 DX-2320: Moved the test data and added redirect
  checkout-v3/display-payment-ui/redirect.md
  checkout-v3/display-payment-ui/seamless-view.md
  checkout-v3/migration-guide.md
  checkout-v3/release-notes.md
  checkout-v3/test-data.md
Labels: documentation

#2094 DX-2341: Added info regarding the new token error types
  _includes/problems/checkout.md
Labels: documentation

#2095 DX-2342: Removed resource cards from DP page
  checkout-v3/index.md
Labels: documentation

#2099 CVM signature flow explained
  pax-terminal/NET/SwpTrmLib/Methods/handy/getpaymentinstrumentasync.md
  pax-terminal/NET/tutorial/cvm-signature.md
Labels: documentation
