Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2024-03, with the labels that each got.

#2148 updated and also a new card under Net
  _includes/pax-netshaddurlacl.md
  pax-terminal/NET/CodeExamples/index.md
  pax-terminal/NET/avoid-privilige-elevation.md
Labels: documentation

#2149 Devp 333 correct example by adding await
  pax-terminal/NET/release-notes.md
  pax-terminal/NET/tutorial/payment-with-orderid.md
Labels: documentation

#2150 Comment on AcuirerData
  _includes/pax-acquirerdata.md
  pax-terminal/NET/includes/acquirerdata.md
  pax-terminal/NET/includes/transactionsetup.md
Labels: documentation

#2153 Changed icon for cards about autconfiguration
  pax-terminal/NET/tutorial/autoconfigurepos.md
  pax-terminal/Nexo-Retailer/auto-configure-ecr-2-terminal.md
Labels: documentation

#2158 DEVP-314: First draft of verify status
  _includes/checkout-v3-events.md
  _includes/fee-discount.md
  _includes/payout.md
  checkout-v3/get-started/fundamental-principles.md
  checkout-v3/get-started/verify-status.md
  checkout-v3/public-migration-key.md
Labels: documentation

#2159 DEVP-341: Sort order of payment menu first draft
  _includes/payment-order-reversal-combined.md
  _includes/sort-order-payment-menu.md
  checkout-v3/features/optional/sort-order-payment-menu.md
  checkout-v3/features/optional/split-settlement.md
  checkout-v3/features/optional/tos.md
  checkout-v3/features/optional/unscheduled.md
  checkout-v3/features/optional/verify.md
Labels: documentation

#2160 DX-343: Get Started feedback from Yvonne
  checkout-v3/get-started/index.md
  checkout-v3/index.md
Labels: documentation

#2161 DEVP-313: Added screenshots in one-click use case
  _includes/use-case-one-click.md
  assets/img/OC1.JPG
  assets/img/PAM1.JPG
Labels: documentation

#2162 DEVP-344: Small sort menu adjustments after feedback
  _includes/sort-order-payment-menu.md
  checkout-v3/get-started/display-payment-ui/index.md
Labels: documentation

#2164 DEVP-345: Added padding to Get Started illustration
  checkout-v3/get-started/index.md
Labels: documentation

#2165 DEVP-342: Validate status feedback
  checkout-v3/get-started/validate-status.md
Labels: documentation

#2163 Develop pos
  _includes/pax-acquirerdata.md
  _includes/pax-netshaddurlacl.md
  pax-terminal/NET/CodeExamples/index.md
  pax-terminal/NET/avoid-privilige-elevation.md
  pax-terminal/NET/includes/acquirerdata.md
  pax-terminal/NET/includes/transactionsetup.md
  pax-terminal/NET/release-notes.md
  pax-terminal/NET/tutorial/autoconfigurepos.md
  pax-terminal/NET/tutorial/payment-with-orderid.md
  pax-terminal/Nexo-Retailer/auto-configure-ecr-2-terminal.md
  pax-terminal/Nexo-Retailer/submit-purchse-order-number.md
Labels: documentation

#2166 DEVP-317: Added info about available implementations and how long the link lives
  _includes/payment-link.md
Labels: documentation

#2169 DEVP-346: Renamed consent checkbox, moved section a bit, added a usage restriction
  _includes/one-click-payments.md
Labels: documentation

#2170 DEVP-347: Added new checkbox text after feedback from William
  _includes/one-click-payments.md
  _includes/sort-order-payment-menu.md
  checkout-v3/features/optional/sort-order-payment-menu.md
Labels: documentation

#2171 Fixed left menu that was hidden.
  pax-terminal/NET/SwpTrmLib/Events/index.md
  pax-terminal/NET/SwpTrmLib/ISwpTrmCallbackInterface/index.md
  pax-terminal/NET/avoid-privilige-elevation.md
  pax-terminal/NET/includes/acquirerdata.md
  pax-terminal/NET/tutorial/apmtransaction.md
  pax-terminal/NET/tutorial/autoconfigurepos.md
  pax-terminal/NET/tutorial/cvm-signature.md
  pax-terminal/NET/tutorial/fuel-card-transaction.md
  pax-terminal/NET/tutorial/payment-with-orderid.md
Labels: documentation

#2172 DX-265: Added tables to migration guide and did other changes.
  checkout-v3/migration-guide.md
Labels: documentation

#2173 DEVP-349: Updated from 2.2.4 to 2.2.6
  Gemfile
  Gemfile.lock
Labels: development

#2175 DEVP-347: cleanup before release 5.0.0
  Gemfile
  Gemfile.lock
  _includes/one-click-payments.md
  _includes/payment-link.md
  _includes/sort-order-payment-menu.md
  _includes/use-case-one-click.md
  checkout-v3/features/optional/delete-token.md
  checkout-v3/features/optional/fees-discounts.md
  checkout-v3/features/optional/instrument-mode.md
  checkout-v3/features/optional/integrated-commerce.md
  checkout-v3/features/optional/moto.md
  checkout-v3/features/optional/network-tokenization.md
  checkout-v3/features/optional/one-click-payments.md
  checkout-v3/features/optional/order-items.md
  checkout-v3/features/optional/payer-aware-payment-menu.md
  checkout-v3/features/optional/payer-restrictions.md
  checkout-v3/features/optional/payment-link.md
  checkout-v3/features/optional/payout.md
  checkout-v3/features/optional/recur.md
  checkout-v3/features/optional/request-delivery-info.md
  checkout-v3/features/optional/sort-order-payment-menu.md
  checkout-v3/get-started/index.md
  checkout-v3/release-notes.md
Labels: documentation, development

#2177 Release 5.0.0 (develop)
  checkout-v3/release-notes.md
Labels: documentation

#2178 DEVP-351: Changed format of the restrictedToIntruments array
  _includes/sort-order-payment-menu.md
Labels: documentation

#2174 SDK-1: Update of Mobile SDK documentation
  _config.yml
  checkout-v3/modules-sdks/mobile-sdk/android.md
  checkout-v3/modules-sdks/mobile-sdk/bare-minimum-implementation.md
  checkout-v3/modules-sdks/mobile-sdk/configuration.md
  checkout-v3/modules-sdks/mobile-sdk/custom-backend.md
  checkout-v3/modules-sdks/mobile-sdk/features/index.md
  checkout-v3/modules-sdks/mobile-sdk/index.md
  checkout-v3/modules-sdks/mobile-sdk/ios.md
  checkout-v3/modules-sdks/mobile-sdk/merchant-backend-sample-code.md
  checkout-v3/modules-sdks/mobile-sdk/merchant-backend-v2.md
  checkout-v3/modules-sdks/mobile-sdk/merchant-backend.md
  checkout-v3/modules-sdks/mobile-sdk/plain-webview.md
  checkout-v3/modules-sdks/mobile-sdk/process-diagrams.md
  checkout-v3/payment-presentations.md
Labels: documentation, config
