Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2025-04, with the labels that each got.

#2528 Fixed release notes format, card and title
  release-notes/index.md
  release-notes/payment-terminals.md
Labels: documentation

#2530 Release 5.3.6 (develop)
  release-notes/digital-payments.md
  release-notes/pay-softpos.md
Labels: documentation

#2532 Removed release notes in dp for develop-main too
  checkout-v3/release-notes.md
Labels: documentation

#2541 Added Go Cloud FAQ draft
  checkout-v3/get-started/fundamental-principles.md
Labels: documentation

#2547 hotfix devp-577 char length payeereference (master)
  _includes/autoclick.md
  _includes/cancel.md
  _includes/capture.md
  _includes/card-authorization-transaction.md
  _includes/card-payments-capture.md
  _includes/checkout-v2-resource-models.md
  _includes/checkout-v2-status-models.md
  _includes/checkout-v3-resource-models.md
  _includes/checkout-v3-status-models.md
  _includes/checkoutv3-purchase.md
  _includes/corporate-limited-menu.md
  _includes/fields/payee-reference.md
  _includes/integrated-commerce.md
  _includes/invoice-authorization-transaction.md
  _includes/mobilepay-payments-capture.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-cancel-3-1.md
  _includes/payment-order-cancel-combined.md
  _includes/payment-order-cancel.md
  _includes/payment-order-capture-combined.md
  _includes/payment-order-capture.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
  _includes/payment-order-reversal-combined.md
  _includes/payment-order-reversal.md
  _includes/payment-order-unscheduled.md
  _includes/payment-request-3-0.md
  _includes/payment-request-3-1.md
  _includes/payout.md
  _includes/post-purchase-3-0.md
  _includes/post-purchase-3-1.md
  _includes/purchase.md
  _includes/recurring-card-payments.md
  _includes/request-delivery-info.md
  _includes/reversal.md
  _includes/tra.md
  _includes/transaction-list-response.md
  _includes/transaction-response.md
  _includes/unscheduled-purchase.md
  _includes/vipps-payments-capture.md
  old-implementations/payment-instruments-v1/card/after-payment.md
  old-implementations/payment-instruments-v1/invoice/direct.md
  old-implementations/payment-instruments-v1/invoice/redirect.md
  old-implementations/payment-instruments-v1/invoice/seamless-view.md
  old-implementations/payment-instruments-v1/mobile-pay/after-payment.md
  old-implementations/payment-instruments-v1/mobile-pay/redirect.md
  old-implementations/payment-instruments-v1/mobile-pay/seamless-view.md
  old-implementations/payment-instruments-v1/swish/after-payment.md
  old-implementations/payment-instruments-v1/swish/direct.md
  old-implementations/payment-instruments-v1/swish/redirect.md
  old-implementations/payment-instruments-v1/swish/seamless-view.md
  old-implementations/payment-instruments-v1/vipps/after-payment.md
  old-implementations/payment-instruments-v1/vipps/redirect.md
  old-implementations/payment-instruments-v1/vipps/seamless-view.md
Labels: documentation, fix

#2552 Re-arranged apple pay domain verification info
  checkout-v3/apple-pay-presentation.md
Labels: documentation

#2553 Added end of date for whitelist grace period
  _includes/callback-3-0.md
  _includes/callback-3-1.md
Labels: documentation

#2554 Added missing string(30) on payeeReference (master)
  _includes/payee-info.md
  _includes/payment-order-capture-3-1.md
  _includes/payment-order-capture-combined.md
  _includes/payment-order-capture.md
  _includes/payment-order-recur.md
  _includes/payment-order-reversal-3-1.md
  _includes/payment-order-reversal-combined.md
  _includes/payment-order-reversal.md
  _includes/payment-order-unscheduled.md
  _includes/payments-operations.md
  _includes/post-purchase-3-0.md
  _includes/post-purchase-3-1.md
  old-implementations/payment-instruments-v1/invoice/after-payment.md
  old-implementations/payment-instruments-v1/mobile-pay/after-payment.md
  old-implementations/payment-instruments-v1/trustly/after-payment.md
Labels: documentation, fix

#2555 Hotfix devp-579 hotfix of payeereference hotfix (develop)
  _includes/payee-info.md
  _includes/payment-order-capture-3-1.md
  _includes/payment-order-capture-combined.md
  _includes/payment-order-capture.md
  _includes/payment-order-recur.md
  _includes/payment-order-reversal-3-1.md
  _includes/payment-order-reversal-combined.md
  _includes/payment-order-reversal.md
  _includes/payment-order-unscheduled.md
  _includes/payments-operations.md
  _includes/post-purchase-3-0.md
  _includes/post-purchase-3-1.md
  old-implementations/payment-instruments-v1/invoice/after-payment.md
  old-implementations/payment-instruments-v1/mobile-pay/after-payment.md
  old-implementations/payment-instruments-v1/trustly/after-payment.md
Labels: documentation, fix

#2556 Hotfix devp 579 hotfix of payeereference hotfix (develop-ecom)
  _includes/payee-info.md
  _includes/payment-order-capture-3-1.md
  _includes/payment-order-capture-combined.md
  _includes/payment-order-capture.md
  _includes/payment-order-recur.md
  _includes/payment-order-reversal-3-1.md
  _includes/payment-order-reversal-combined.md
  _includes/payment-order-reversal.md
  _includes/payment-order-unscheduled.md
  _includes/payments-operations.md
  _includes/post-purchase-3-0.md
  _includes/post-purchase-3-1.md
  old-implementations/payment-instruments-v1/invoice/after-payment.md
  old-implementations/payment-instruments-v1/mobile-pay/after-payment.md
  old-implementations/payment-instruments-v1/trustly/after-payment.md
Labels: documentation, fix

#2557 Added two callback FAQs
  _includes/callback-3-0.md
  _includes/callback-3-1.md
Labels: documentation

#2559 Release 5.3.7 (master)
  Gemfile
  Gemfile.lock
  _includes/callback-3-0.md
  _includes/callback-3-1.md
  _includes/callback.md
  _includes/create-payment.md
  _includes/problems/checkout.md
  _includes/problems/old-implementations/payment-instruments-v1/checkout.md
  _includes/problems/old-implementations/payment-instruments-v1/swish.md
  _includes/problems/swish.md
  _includes/settlement-reconciliation.md
  _includes/split-settlement.md
  _includes/use-case-one-click.md
  checkout-v3/apple-pay-presentation.md
  checkout-v3/get-started/fundamental-principles.md
  checkout-v3/get-started/index.md
  checkout-v3/get-started/terminology.md
  old-implementations/mobile-sdk/merchant-backend-v2.md
  old-implementations/mobile-sdk/merchant-backend.md
  package-lock.json
  package.json
  release-notes/digital-payments.md
Labels: documentation, development

#2560 Release 5.3.7 (develop)
  release-notes/digital-payments.md
Labels: documentation

#2562 Changed monitoring the script url text
  checkout-v3/get-started/display-payment-ui/seamless-view.md
  checkout-v3/get-started/display-payment-ui/ui-migration.md
  old-implementations/checkout-v2/checkin.md
  old-implementations/checkout-v2/payment-menu.md
  old-implementations/checkout-v2/ui-migration.md
  old-implementations/payment-instruments-v1/card/seamless-view.md
  old-implementations/payment-instruments-v1/card/ui-migration.md
  old-implementations/payment-menu-v2/payment-order.md
  old-implementations/payment-menu-v2/ui-migration.md
Labels: documentation

#2563 Feature/devp 588 remove payex emails
  _includes/authorizations.md
  _includes/autoclick.md
  _includes/checkout-v3-resource-models.md
  _includes/checkoutv3-purchase.md
  _includes/frictionless-payments.md
  _includes/instrument-mode.md
  _includes/invoice-authorization-transaction.md
  _includes/mobile-sdk-papm.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-moto.md
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
  _includes/payment-order-ssn-restrictions.md
  _includes/payment-order-unscheduled.md
  _includes/payout.md
  _includes/purchase.md
  _includes/request-delivery-info.md
  _includes/tra.md
  _includes/unscheduled-purchase.md
  _includes/use-case-one-click.md
  checkout-v3/get-started/display-payment-ui/seamless-view.md
  checkout-v3/get-started/display-payment-ui/ui-migration.md
  checkout-v3/public-migration-key.md
  checkout-v3/test-data.md
  old-implementations/checkout-v2/checkin.md
  old-implementations/checkout-v2/payment-menu.md
  old-implementations/checkout-v2/ui-migration.md
  old-implementations/payment-instruments-v1/card/seamless-view.md
  old-implementations/payment-instruments-v1/card/ui-migration.md
  old-implementations/payment-instruments-v1/invoice/direct.md
  old-implementations/payment-menu-v2/payment-order.md
  old-implementations/payment-menu-v2/ui-migration.md
Labels: documentation

#2564 Feature/esy 7634 seamless doc
  Gemfile
  Gemfile.lock
  _includes/authorizations.md
  _includes/autoclick.md
  _includes/checkout-v3-events.md
  _includes/checkout-v3-resource-models.md
  _includes/checkoutv3-purchase.md
  _includes/frictionless-payments.md
  _includes/instrument-mode.md
  _includes/invoice-authorization-transaction.md
  _includes/mobile-sdk-papm.md
  _includes/payer-aware-payment-menu.md
  _includes/payment-order-checkout-enterprise.md
  _includes/payment-order-moto.md
  _includes/payment-order-purchase.md
  _includes/payment-order-recur.md
  _includes/payment-order-ssn-restrictions.md
  _includes/payment-order-unscheduled.md
  _includes/payout.md
  _includes/purchase.md
  _includes/request-delivery-info.md
  _includes/tra.md
  _includes/unscheduled-purchase.md
  _includes/use-case-one-click.md
  checkout-v3/get-started/display-payment-ui/redirect.md
  checkout-v3/get-started/display-payment-ui/seamless-view.md
  checkout-v3/public-migration-key.md
  checkout-v3/test-data.md
  old-implementations/payment-instruments-v1/invoice/direct.md
  release-notes/digital-payments.md
Labels: documentation, development
