Repository SwedbankPay/developer.swedbankpay.com, pull requests merged in 2025-02, with the labels that each got.

#2480 DEVP-259: Added more presentations
  checkout-v3/click-to-pay-presentation.md
  checkout-v3/google-pay-presentation.md
  checkout-v3/index.md
  checkout-v3/mobilepay-presentation.md
  checkout-v3/trustly-presentation.md
  checkout-v3/vipps-presentation.md
Labels: documentation

#2482 DEVP-521: Moved library back to unsupported.
  checkout-v3/modules-sdks/index.md
Labels: documentation

#2483 DEVP-522: Renaming and re-launching.
  checkout-v3/get-started/index.md
  checkout-v3/migrate.md
  checkout-v3/migration-guide-v1.md
  checkout-v3/migration-guide-v2.md
  checkout-v3/release-notes.md
  old-implementations/checkout-v2/ui-migration.md
  old-implementations/index.md
  old-implementations/payment-menu-v2/ui-migration.md
Labels: documentation

#2484 DEVP-523: Gave all presentations (minus card) the same intro layout
  checkout-v3/card-presentation.md
  checkout-v3/click-to-pay-presentation.md
  checkout-v3/google-pay-presentation.md
  checkout-v3/mobilepay-presentation.md
  checkout-v3/trustly-presentation.md
  checkout-v3/vipps-presentation.md
Labels: documentation

#2486 DEVP-525: Last input before release.
  _includes/callback.md
  _includes/payment-order-3-1.md
  _includes/payment-order-checkout-payments-only.md
  checkout-v3/migration-guide-v1.md
Labels: documentation

#2489 Release 5.3.4 (develop)
  checkout-v3/release-notes.md
Labels: documentation

#1699 Update instrument-mode.md
  _includes/instrument-mode.md
Labels: documentation

#2491 First draft of SoftPos section
  pax-terminal/softpos.md
Labels: documentation

#2492 DEVP-532: A few fixes
  pax-terminal/softpos.md
Labels: documentation

#2493 Hotfix: DEVP-535 - Changed format of the IP addresses (master)
  _includes/callback.md
Labels: documentation, fix

#2494 Hotfix: DEVP-535 - Changed format of the IP addresses (develop)
  _includes/callback.md
Labels: documentation, fix

#2490 DEVP-315: Fixing the last issues from the task.
  _includes/one-click-payments.md
Labels: documentation

#2500 DEVP-540: Header downgrade and text in disclaimer
  _includes/callback.md
Labels: documentation

#2503 DEVP-543: Fixed format of IP addresses
  _includes/callback.md
Labels: documentation

#2504 Release 5.3.5 (master)
  Gemfile
  Gemfile.lock
  _includes/callback.md
  _includes/instrument-mode.md
  _includes/one-click-payments.md
  checkout-v3/release-notes.md
  pax-terminal/Nexo-Retailer/index.md
  pax-terminal/softpos.md
Labels: documentation, development

#2505 Release 5.3.5 (develop)
  checkout-v3/release-notes.md
Labels: documentation

#2508 A bunch of Swish presentation changes after feedback
  checkout-v3/get-started/payment-request-3-1.md
  checkout-v3/get-started/payment-request.md
  checkout-v3/index.md
  checkout-v3/swish-presentation.md
Labels: documentation
